import {NextResponse} from'next/server'
import {sql} from'../../../lib/db'
import {getSession} from'../../../lib/auth'
async function auth(){const s=await getSession();if(!s)return{error:NextResponse.json({error:'No autorizado'},{status:401})};return{session:s}}
function productsOf(b){const src=Array.isArray(b.products)?b.products:[];return src.map(p=>({inventory_id:Number(p.inventory_id||0),product_name:String(p.product_name||'').trim(),quantity:Number(p.quantity),unit:'sacos',price_per_sack:Number(p.price_per_sack||0)})).filter(p=>p.inventory_id||p.product_name||p.quantity||p.price_per_sack)}
function payload(b){const products=productsOf(b),total_cost=products.reduce((s,p)=>s+p.quantity*p.price_per_sack,0);return{application_date:String(b.application_date||'').slice(0,10),farm_id:Number(b.farm_id),abonada_number:Number(b.abonada_number),products,treated_area_ha:b.treated_area_ha===''||b.treated_area_ha==null?null:Number(b.treated_area_ha),total_cost,responsible:String(b.responsible||'').trim(),notes:String(b.notes||'').trim()}}
function validate(x){if(!x.application_date||!x.farm_id)return'Fecha y finca son requeridas.';if(![1,2,3].includes(x.abonada_number))return'Seleccione Abonada 1, 2 o 3.';if(!x.products.length)return'Debe registrar al menos un abono.';for(const p of x.products){if(!p.inventory_id)return'Seleccione cada abono desde Inventario Productos de Café.';if(!(p.quantity>0))return'La cantidad de sacos debe ser mayor que cero.';if(p.price_per_sack<0)return'El precio por saco no puede ser negativo.'}if(x.treated_area_ha!=null&&!(x.treated_area_ha>0))return'El área abonada debe ser mayor que cero.';return''}
function dbError(e,action='registrar'){console.error('coffee-abonadas',e?.code,e?.constraint,e?.message);if(e?.code==='23514')return NextResponse.json({error:'Un dato no cumple las reglas de la abonada. Revise sacos, precio y área.'},{status:400});if(e?.code==='23503')return NextResponse.json({error:'La finca, lote o usuario ya no existe. Actualice la página e intente de nuevo.'},{status:400});return NextResponse.json({error:`No se pudo ${action} la abonada. Código técnico: ${e?.code||'DB'}.`},{status:500})}
export async function GET(){const a=await auth();if(a.error)return a.error;try{const rows=await sql`SELECT r.*,COALESCE((SELECT json_agg(json_build_object('id',p.id,'inventory_id',p.inventory_id,'product_name',p.product_name,'quantity',p.quantity,'unit',p.unit,'price_per_sack',p.price_per_sack,'subtotal',p.quantity*p.price_per_sack,'lot_number',i.lot_number,'expiration_date',i.expiration_date) ORDER BY p.id) FROM public.coffee_abonada_products p LEFT JOIN public.coffee_inventory i ON i.id=p.inventory_id WHERE p.abonada_id=r.id),'[]'::json) AS product_list FROM public.coffee_abonada_report r ORDER BY r.application_date DESC,r.id DESC`;return NextResponse.json({abonadas:rows})}catch(e){return dbError(e,'cargar')}}
export async function POST(req){const a=await auth();if(a.error)return a.error;if(a.session.role!=='admin')return NextResponse.json({error:'Solo administrador.'},{status:403});try{const x=payload(await req.json()),e=validate(x);if(e)return NextResponse.json({error:e},{status:400});const productsJson=JSON.stringify(x.products);const rows=await sql`WITH p AS (SELECT * FROM jsonb_to_recordset(${productsJson}::jsonb) AS p(inventory_id bigint,product_name text,quantity numeric,unit text,price_per_sack numeric)),demand AS (SELECT inventory_id,SUM(quantity) quantity FROM p GROUP BY inventory_id),chk AS (SELECT COUNT(*)=(SELECT COUNT(*) FROM demand) AND COALESCE(BOOL_AND(i.id IS NOT NULL AND i.active AND i.category='Abono' AND i.unit='sacos' AND i.farm_id IS NULL AND i.current_stock>=d.quantity),false) AS ok FROM demand d LEFT JOIN public.coffee_inventory i ON i.id=d.inventory_id),ins AS (INSERT INTO public.coffee_abonadas(application_date,farm_id,method,abonada_number,treated_area_ha,total_cost,responsible,notes,created_by,updated_by) SELECT ${x.application_date},${x.farm_id},'Manual',${x.abonada_number},${x.treated_area_ha},${x.total_cost},${x.responsible||null},${x.notes||null},${a.session.id},${a.session.id} FROM chk WHERE ok RETURNING id),prod AS (INSERT INTO public.coffee_abonada_products(abonada_id,inventory_id,product_name,quantity,unit,price_per_sack) SELECT ins.id,p.inventory_id,i.name,p.quantity,'sacos',p.price_per_sack FROM ins CROSS JOIN p JOIN public.coffee_inventory i ON i.id=p.inventory_id RETURNING abonada_id),mov AS (INSERT INTO public.coffee_inventory_movements(inventory_id,movement_date,movement_type,quantity,unit_cost,farm_id,reference_type,reference_id,notes,created_by) SELECT d.inventory_id,${x.application_date},'salida',d.quantity,i.unit_cost,${x.farm_id},'abonada',ins.id,${`Abonada ${x.abonada_number} · Lote exacto`},${a.session.id} FROM demand d JOIN public.coffee_inventory i ON i.id=d.inventory_id CROSS JOIN ins RETURNING id) SELECT (SELECT id FROM ins) id,(SELECT ok FROM chk) inventory_ok`;if(!rows[0]?.inventory_ok||!rows[0]?.id)return NextResponse.json({error:'No se pudo descontar el lote seleccionado. Verifique la existencia disponible.'},{status:400});return NextResponse.json({ok:true,id:rows[0].id,total_cost:x.total_cost})}catch(e){return dbError(e,'registrar')}}
export async function PATCH(){return NextResponse.json({error:'Para proteger la trazabilidad por lote, la edición de abonadas está temporalmente deshabilitada mientras se migra el historial anterior.'},{status:409})}
