import {NextResponse} from'next/server'
import {sql} from'../../../lib/db'
import {getSession} from'../../../lib/auth'
const METHODS=['Dron','Manual','Maquina estacionaria']
async function auth(){const s=await getSession();if(!s)return{error:NextResponse.json({error:'No autorizado'},{status:401})};return{session:s}}
function payload(b){const application_cost=Number(b.application_cost||0);return{application_date:String(b.application_date||'').slice(0,10),farm_id:Number(b.farm_id),method:String(b.method||''),treated_area_ha:b.treated_area_ha===''||b.treated_area_ha==null?null:Number(b.treated_area_ha),application_cost,total_cost:application_cost,responsible:String(b.responsible||'').trim(),notes:String(b.notes||'').trim()}}
function validate(x){if(!x.application_date||!x.farm_id||!METHODS.includes(x.method))return'Fecha, finca y método son requeridos.';if(x.treated_area_ha!=null&&!(x.treated_area_ha>0))return'El área tratada debe ser mayor que cero.';if(x.application_cost<0)return'El costo de aplicación no puede ser negativo.';return''}
function dbError(e,action='registrar'){console.error('coffee-fertilizations',e?.code,e?.constraint,e?.message);if(e?.code==='23514')return NextResponse.json({error:'Revise el costo y el área tratada.'},{status:400});if(e?.code==='23503')return NextResponse.json({error:'La finca o usuario ya no existe. Actualice la página.'},{status:400});return NextResponse.json({error:`No se pudo ${action} la atomización. Código técnico: ${e?.code||'DB'}.`},{status:500})}
export async function GET(){const a=await auth();if(a.error)return a.error;try{const rows=await sql`SELECT r.*,COALESCE((SELECT json_agg(json_build_object('id',p.id,'inventory_id',p.inventory_id,'product_name',p.product_name,'quantity',p.quantity,'unit',p.unit,'unit_cost',p.unit_cost,'subtotal',p.quantity*p.unit_cost,'lot_number',i.lot_number,'expiration_date',i.expiration_date) ORDER BY p.id) FROM public.coffee_fertilization_products p LEFT JOIN public.coffee_inventory i ON i.id=p.inventory_id WHERE p.fertilization_id=r.id),'[]'::json) AS product_list FROM public.coffee_fertilization_report r ORDER BY r.application_date DESC,r.id DESC`;return NextResponse.json({fertilizations:rows})}catch(e){return dbError(e,'cargar')}}
export async function POST(req){const a=await auth();if(a.error)return a.error;if(a.session.role!=='admin')return NextResponse.json({error:'Solo administrador.'},{status:403});try{const x=payload(await req.json()),e=validate(x);if(e)return NextResponse.json({error:e},{status:400});const rows=await sql`INSERT INTO public.coffee_fertilizations(application_date,farm_id,method,product_name,quantity,unit,treated_area_ha,total_cost,application_cost,responsible,notes,created_by,updated_by) VALUES(${x.application_date},${x.farm_id},${x.method},'Solo costo de aplicación',1,'aplicación',${x.treated_area_ha},${x.total_cost},${x.application_cost},${x.responsible||null},${x.notes||null},${a.session.id},${a.session.id}) RETURNING id`;return NextResponse.json({ok:true,id:rows[0].id,total_cost:x.total_cost})}catch(e){return dbError(e,'registrar')}}
export async function PATCH(req){const a=await auth();if(a.error)return a.error;if(a.session.role!=='admin')return NextResponse.json({error:'Solo administrador.'},{status:403});try{const b=await req.json(),id=Number(b.id);if(!id)return NextResponse.json({error:'Registro requerido.'},{status:400});const x=payload(b),e=validate(x);if(e)return NextResponse.json({error:e},{status:400});const rows=await sql`UPDATE public.coffee_fertilizations SET application_date=${x.application_date},farm_id=${x.farm_id},method=${x.method},treated_area_ha=${x.treated_area_ha},total_cost=${x.total_cost},application_cost=${x.application_cost},responsible=${x.responsible||null},notes=${x.notes||null},updated_by=${a.session.id},updated_at=now() WHERE id=${id} RETURNING id`;if(!rows[0]?.id)return NextResponse.json({error:'La atomización ya no existe.'},{status:404});return NextResponse.json({ok:true,id:rows[0].id,total_cost:x.total_cost})}catch(e){return dbError(e,'editar')}}
