import {NextResponse} from'next/server'
import {sql} from'../../../lib/db'
import {getSession} from'../../../lib/auth'

const METHODS=['Dron','Manual','Maquina estacionaria']
async function auth(){const s=await getSession();if(!s)return{error:NextResponse.json({error:'No autorizado'},{status:401})};return{session:s}}
function payload(b){return{application_date:String(b.application_date||'').slice(0,10),farm_id:Number(b.farm_id),method:String(b.method||''),product_name:String(b.product_name||'').trim(),quantity:Number(b.quantity),unit:String(b.unit||'').trim(),treated_area_ha:b.treated_area_ha===''||b.treated_area_ha==null?null:Number(b.treated_area_ha),total_cost:Number(b.total_cost||0),responsible:String(b.responsible||'').trim(),notes:String(b.notes||'').trim()}}
function validate(x){if(!x.application_date||!x.farm_id||!x.product_name||!METHODS.includes(x.method))return'Fecha, finca, método y producto son requeridos.';if(!(x.quantity>0))return'La cantidad debe ser mayor que cero.';if(!x.unit)return'La unidad es requerida.';if(x.treated_area_ha!=null&&!(x.treated_area_ha>0))return'El área tratada debe ser mayor que cero.';if(x.total_cost<0)return'El costo no puede ser negativo.';return''}

export async function GET(){const a=await auth();if(a.error)return a.error;const rows=await sql`SELECT * FROM public.coffee_fertilization_report ORDER BY application_date DESC,id DESC`;return NextResponse.json({fertilizations:rows})}

export async function POST(req){const a=await auth();if(a.error)return a.error;if(a.session.role!=='admin')return NextResponse.json({error:'Solo administrador.'},{status:403});try{const x=payload(await req.json()),e=validate(x);if(e)return NextResponse.json({error:e},{status:400});const rows=await sql`INSERT INTO public.coffee_fertilizations(application_date,farm_id,method,product_name,quantity,unit,treated_area_ha,total_cost,responsible,notes,created_by,updated_by) VALUES(${x.application_date},${x.farm_id},${x.method},${x.product_name},${x.quantity},${x.unit},${x.treated_area_ha},${x.total_cost},${x.responsible||null},${x.notes||null},${a.session.id},${a.session.id}) RETURNING id`;return NextResponse.json({ok:true,id:rows[0]?.id})}catch(e){console.error(e);return NextResponse.json({error:'No se pudo registrar la fertilización.'},{status:500})}}

export async function PATCH(req){const a=await auth();if(a.error)return a.error;if(a.session.role!=='admin')return NextResponse.json({error:'Solo administrador.'},{status:403});try{const b=await req.json(),id=Number(b.id),x=payload(b),e=validate(x);if(!id)return NextResponse.json({error:'Registro requerido.'},{status:400});if(e)return NextResponse.json({error:e},{status:400});await sql`UPDATE public.coffee_fertilizations SET application_date=${x.application_date},farm_id=${x.farm_id},method=${x.method},product_name=${x.product_name},quantity=${x.quantity},unit=${x.unit},treated_area_ha=${x.treated_area_ha},total_cost=${x.total_cost},responsible=${x.responsible||null},notes=${x.notes||null},updated_by=${a.session.id},updated_at=now() WHERE id=${id}`;return NextResponse.json({ok:true})}catch(e){console.error(e);return NextResponse.json({error:'No se pudo actualizar la fertilización.'},{status:500})}}
