'use client'
import {useEffect,useMemo,useState} from'react'

const productBlank={product_name:'',quantity:'',unit:'kg'}
const blank={application_date:'',farm_id:'',method:'Dron',products:[productBlank],treated_area_ha:'',total_cost:'',responsible:'',notes:''}
function money(v){return`₡${Number(v||0).toLocaleString('es-CR',{maximumFractionDigits:2})}`}
function dateLabel(v){return v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString('es-CR'):'—'}

export default function CoffeeFertilization({farms,user}){
 const isAdmin=user?.role==='admin',activeFarms=useMemo(()=>farms.filter(f=>f.active),[farms])
 const[rows,setRows]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[filterFarm,setFilterFarm]=useState(''),[filterMethod,setFilterMethod]=useState(''),[msg,setMsg]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{load()},[])
 async function load(){const r=await fetch('/api/coffee-fertilizations',{cache:'no-store'}),d=await r.json();if(r.ok)setRows(d.fertilizations||[]);else setErr(d.error||'No se pudieron cargar las fertilizaciones.')}
 function reset(){setForm({...blank,products:[{...productBlank}]});setEditing(null)}
 function edit(x){setEditing(x.id);const products=Array.isArray(x.product_list)&&x.product_list.length?x.product_list.map(p=>({product_name:p.product_name||'',quantity:String(p.quantity||''),unit:p.unit||'kg'})):[{product_name:x.product_name||'',quantity:String(x.quantity||''),unit:x.unit||'kg'}];setForm({application_date:String(x.application_date).slice(0,10),farm_id:String(x.farm_id),method:x.method,products,treated_area_ha:x.treated_area_ha??'',total_cost:String(x.total_cost||0),responsible:x.responsible||'',notes:x.notes||''})}
 function setProduct(i,k,v){setForm(f=>({...f,products:f.products.map((p,n)=>n===i?{...p,[k]:v}:p)}))}
 function addProduct(){setForm(f=>({...f,products:[...f.products,{...productBlank}]}))}
 function removeProduct(i){setForm(f=>({...f,products:f.products.length>1?f.products.filter((_,n)=>n!==i):f.products}))}
 async function save(e){e.preventDefault();setBusy(true);setErr('');setMsg('');try{const r=await fetch('/api/coffee-fertilizations',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,id:editing})}),d=await r.json();if(!r.ok){setErr(d.error||'No se pudo guardar.');return}setMsg(editing?'Fertilización actualizada correctamente.':`Fertilización registrada con ${d.products||form.products.length} producto(s).`);reset();await load()}finally{setBusy(false)}}
 const filtered=useMemo(()=>rows.filter(x=>(!filterFarm||String(x.farm_id)===filterFarm)&&(!filterMethod||x.method===filterMethod)),[rows,filterFarm,filterMethod])
 const summary=useMemo(()=>filtered.reduce((a,x)=>{a.apps++;a.cost+=Number(x.total_cost||0);a.area+=Number(x.treated_area_ha||0);a.farms.add(String(x.farm_id));return a},{apps:0,cost:0,area:0,farms:new Set()}),[filtered])
 return <div className="fertilization-module"><div className="section-heading"><div><h2>Fertilización de café</h2><p>Registre una aplicación y agregue todos los fertilizantes utilizados. El método puede ser Dron, Manual o Máquina estacionaria.</p></div></div>
 {msg&&<div className="success-box">{msg}</div>}{err&&<div className="error-box">{err}</div>}
 {isAdmin&&<form className="week-form" onSubmit={save}><div className="week-main-fields"><label>Fecha<input type="date" value={form.application_date} onChange={e=>setForm({...form,application_date:e.target.value})} required/></label><label>Finca<select value={form.farm_id} onChange={e=>setForm({...form,farm_id:e.target.value})} required><option value="">Seleccione finca</option>{activeFarms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Método<select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option>Dron</option><option>Manual</option><option>Maquina estacionaria</option></select></label><label>Área tratada (ha)<input type="number" min="0.001" step="0.001" value={form.treated_area_ha} onChange={e=>setForm({...form,treated_area_ha:e.target.value})}/></label><label>Costo total<input type="number" min="0" step="0.01" value={form.total_cost} onChange={e=>setForm({...form,total_cost:e.target.value})}/></label><label>Responsable<input value={form.responsible} onChange={e=>setForm({...form,responsible:e.target.value})}/></label><label>Observaciones<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>
 <h3>Fertilizantes utilizados</h3><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>#</th><th>Nombre del fertilizante</th><th>Cantidad</th><th>Unidad</th><th>Acción</th></tr></thead><tbody>{form.products.map((p,i)=><tr key={i}><td>{i+1}</td><td><input value={p.product_name} onChange={e=>setProduct(i,'product_name',e.target.value)} placeholder="Ej. 18-5-15-6-0.2" required/></td><td><input type="number" min="0.001" step="0.001" value={p.quantity} onChange={e=>setProduct(i,'quantity',e.target.value)} required/></td><td><select value={p.unit} onChange={e=>setProduct(i,'unit',e.target.value)}><option value="kg">kg</option><option value="L">L</option><option value="sacos">sacos</option><option value="unidades">unidades</option></select></td><td>{form.products.length>1?<button type="button" className="secondary-action" onClick={()=>removeProduct(i)}>Quitar</button>:'—'}</td></tr>)}</tbody></table></div><div className="quick-actions"><button type="button" className="secondary-action" onClick={addProduct}>+ Agregar fertilizante</button><button className="primary-action" disabled={busy}>{editing?'Guardar cambios':'Registrar fertilización'}</button>{editing&&<button type="button" className="secondary-action" onClick={reset}>Cancelar</button>}</div></form>}
 <div className="week-main-fields" style={{marginTop:18}}><label>Filtrar por finca<select value={filterFarm} onChange={e=>setFilterFarm(e.target.value)}><option value="">Todas</option>{activeFarms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Filtrar por método<select value={filterMethod} onChange={e=>setFilterMethod(e.target.value)}><option value="">Todos</option><option>Dron</option><option>Manual</option><option>Maquina estacionaria</option></select></label><button type="button" className="secondary-action" onClick={()=>{setFilterFarm('');setFilterMethod('')}}>Limpiar filtros</button></div>
 <div className="pay-preview"><span>Aplicaciones<strong>{summary.apps}</strong></span><span>Fincas<strong>{summary.farms.size}</strong></span><span>Área tratada<strong>{summary.area.toFixed(2)} ha</strong></span><span>Costo total<strong>{money(summary.cost)}</strong></span></div>
 <div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Fecha</th><th>Finca</th><th>Método</th><th>Fertilizantes</th><th>Área</th><th>Costo</th><th>Costo/ha</th><th>Responsable</th><th>Observaciones</th>{isAdmin&&<th>Acción</th>}</tr></thead><tbody>{filtered.length?filtered.map(x=><tr key={x.id}><td>{dateLabel(x.application_date)}</td><td><strong>{x.farm_name}</strong></td><td>{x.method}</td><td>{x.products||'—'}</td><td>{x.treated_area_ha?`${Number(x.treated_area_ha).toFixed(2)} ha`:'—'}</td><td>{money(x.total_cost)}</td><td>{x.cost_per_ha==null?'—':money(x.cost_per_ha)}</td><td>{x.responsible||'—'}</td><td>{x.notes||'—'}</td>{isAdmin&&<td><button type="button" className="secondary-action" onClick={()=>edit(x)}>Editar</button></td>}</tr>):<tr><td colSpan={isAdmin?10:9} className="empty-cell">Aún no hay fertilizaciones registradas.</td></tr>}</tbody></table></div></div>
}
