'use client'
import {useEffect,useMemo,useState} from'react'

function money(v){return`₡${Number(v||0).toLocaleString('es-CR',{maximumFractionDigits:2})}`}
function harvestDate(v){return v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString('es-CR'):'—'}
function registeredAt(v){return v?new Date(v).toLocaleString('es-CR',{dateStyle:'short',timeStyle:'short'}):'—'}
function legacyMeasure(x){const n=Number(x.measure_number);if(n>0)return n;const m=String(x.notes||'').match(/Medida\s+(\d+)/i);return Number(m?.[1]||1)}
function cleanNotes(x){return String(x.notes||'').replace(/^Medida\s+\d+\s*:\s*/i,'').replace(/^Medida\s+\d+$/i,'').trim()||'—'}

export default function CoffeeMeasureHistory({farms}){
 const[rows,setRows]=useState([]),[date,setDate]=useState(''),[farm,setFarm]=useState(''),[worker,setWorker]=useState(''),[open,setOpen]=useState(true)
 useEffect(()=>{load();const f=()=>load();window.addEventListener('coffee-harvest-updated',f);return()=>window.removeEventListener('coffee-harvest-updated',f)},[])
 async function load(){const r=await fetch('/api/coffee-harvest',{cache:'no-store'}),d=await r.json();if(r.ok)setRows(d.harvest||[])}
 const workers=useMemo(()=>{const m=new Map();rows.forEach(x=>m.set(String(x.worker_id),x.worker_name));return[...m.entries()].sort((a,b)=>String(a[1]).localeCompare(String(b[1])))},[rows])
 const filtered=useMemo(()=>rows.filter(x=>(!date||String(x.harvest_date).slice(0,10)===date)&&(!farm||String(x.farm_id)===farm)&&(!worker||String(x.worker_id)===worker)),[rows,date,farm,worker])
 return <section className="farms-module coffee-history" style={{marginTop:20}}><div className="farms-toolbar"><div><h2>Historial de medidas registradas</h2><p className="muted">Cada medida conserva el día de cosecha, la fecha y hora exacta de registro, el peón, la finca y el número formal de medida.</p></div><button type="button" className="secondary-action" onClick={()=>setOpen(v=>!v)}>{open?'Ocultar':'Mostrar historial'}</button></div>{open&&<><div className="week-main-fields"><label>Día de cosecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Finca<select value={farm} onChange={e=>setFarm(e.target.value)}><option value="">Todas las fincas</option>{farms.filter(f=>f.active).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Peón<select value={worker} onChange={e=>setWorker(e.target.value)}><option value="">Todos los peones</option>{workers.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><div className="quick-actions"><button type="button" className="secondary-action" onClick={()=>{setDate('');setFarm('');setWorker('')}}>Limpiar filtros</button><button type="button" className="secondary-action" onClick={load}>Actualizar</button></div></div><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Día de cosecha</th><th>Fecha y hora de registro</th><th>Peón</th><th>Finca</th><th>Medida</th><th>Cajuelas</th><th>Precio/cajuela</th><th>Total</th><th>Observación</th></tr></thead><tbody>{filtered.length?filtered.map(x=><tr key={x.id}><td>{harvestDate(x.harvest_date)}</td><td><strong>{registeredAt(x.created_at)}</strong></td><td>{x.worker_name}</td><td>{x.farm_name}</td><td><strong>Medida {legacyMeasure(x)}</strong></td><td>{Number(x.quantity||0).toFixed(2)}</td><td>{money(x.rate_per_unit)}</td><td><strong>{money(x.amount)}</strong></td><td>{cleanNotes(x)}</td></tr>):<tr><td colSpan="9" className="empty-cell">No hay medidas registradas para estos filtros.</td></tr>}</tbody></table></div><p className="muted" style={{marginTop:10}}>{filtered.length} medida(s) mostrada(s).</p></>}</section>
}
