'use client'
import {useEffect,useMemo,useState} from'react'

const productBlank={inventory_id:'',product_name:'',quantity:'',unit:'sacos',price_per_sack:''}
const blank={application_date:'',farm_id:'',products:[{...productBlank}],treated_area_ha:'',responsible:'',notes:''}
function money(v){return`₡${Number(v||0).toLocaleString('es-CR',{minimumFractionDigits:0,maximumFractionDigits:2})}`}
function dateLabel(v){return v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString('es-CR'):'—'}
const hero={background:'linear-gradient(135deg,#6b3f18,#995c22)',color:'#fff',padding:'22px 24px',borderRadius:18,marginBottom:18,boxShadow:'0 10px 28px rgba(107,63,24,.18)'}
const card={background:'#fff',border:'1px solid #eadfd4',borderRadius:18,padding:20,boxShadow:'0 8px 24px rgba(80,54,30,.07)'}

export default function CoffeeAbonada({farms,user}){
 const isAdmin=user?.role==='admin',activeFarms=useMemo(()=>farms.filter(f=>f.active),[farms])
 const[rows,setRows]=useState([]),[inventory,setInventory]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[filterFarm,setFilterFarm]=useState(''),[msg,setMsg]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{load()},[])
 async function load(){const[r1,r2]=await Promise.all([fetch('/api/coffee-abonadas',{cache:'no-store'}),fetch('/api/coffee-inventory',{cache:'no-store'})]);const[d1,d2]=await Promise.all([r1.json(),r2.json()]);if(r1.ok)setRows(d1.abonadas||[]);else setErr(d1.error||'No se pudieron cargar las abonadas.');if(r2.ok)setInventory((d2.products||[]).filter(x=>x.active&&x.category==='Abono'&&x.unit==='sacos'))}
 const availableInventory=useMemo(()=>inventory.filter(x=>!form.farm_id||!x.farm_id||String(x.farm_id)===String(form.farm_id)),[inventory,form.farm_id])
 function reset(){setForm({...blank,products:[{...productBlank}]});setEditing(null)}
 function matchInventory(p,farmId){return inventory.find(i=>i.active&&String(i.product_name).trim().toLowerCase()===String(p.product_name||'').trim().toLowerCase()&&i.unit==='sacos'&&(!i.farm_id||String(i.farm_id)===String(farmId)))}
 function edit(x){setEditing(x.id);const products=(x.product_list||[]).map(p=>{const inv=matchInventory(p,x.farm_id);return{inventory_id:inv?String(inv.id):'',product_name:p.product_name||'',quantity:String(p.quantity||''),unit:'sacos',price_per_sack:String(p.price_per_sack||0)}});setForm({application_date:String(x.application_date).slice(0,10),farm_id:String(x.farm_id),products:products.length?products:[{...productBlank}],treated_area_ha:x.treated_area_ha??'',responsible:x.responsible||'',notes:x.notes||''})}
 function setProduct(i,k,v){setForm(f=>({...f,products:f.products.map((p,n)=>n===i?{...p,[k]:v}:p)}))}
 function chooseInventory(i,id){const inv=inventory.find(x=>String(x.id)===String(id));if(!inv)return setProduct(i,'inventory_id','');setForm(f=>({...f,products:f.products.map((p,n)=>n===i?{...p,inventory_id:String(inv.id),product_name:inv.product_name,unit:'sacos',price_per_sack:String(inv.unit_cost||0)}:p)}))}
 function addProduct(){setForm(f=>({...f,products:[...f.products,{...productBlank}]}))}
 function removeProduct(i){setForm(f=>({...f,products:f.products.length>1?f.products.filter((_,n)=>n!==i):f.products}))}
 const totalNow=useMemo(()=>form.products.reduce((s,p)=>s+Number(p.quantity||0)*Number(p.price_per_sack||0),0),[form.products])
 async function save(e){e.preventDefault();setBusy(true);setErr('');setMsg('');try{const r=await fetch('/api/coffee-abonadas',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,id:editing})}),d=await r.json();if(!r.ok){setErr(d.error||'No se pudo guardar.');return}setMsg(editing?'Abonada actualizada y existencia corregida.':`Abonada registrada y descontada del inventario. Total: ${money(d.total_cost)}`);reset();await load()}finally{setBusy(false)}}
 const filtered=useMemo(()=>rows.filter(x=>!filterFarm||String(x.farm_id)===filterFarm),[rows,filterFarm])
 const summary=useMemo(()=>filtered.reduce((a,x)=>{a.apps++;a.cost+=Number(x.total_cost||0);a.area+=Number(x.treated_area_ha||0);a.farms.add(String(x.farm_id));return a},{apps:0,cost:0,area:0,farms:new Set()}),[filtered])
 return <div className="fertilization-module">
  <div style={hero}><div style={{fontSize:13,opacity:.8,fontWeight:700,letterSpacing:1}}>CAFÉ · FERTILIZACIÓN AL SUELO</div><h2 style={{margin:'6px 0 4px',fontSize:30}}>🧺 Abonada</h2><p style={{margin:0,opacity:.92}}>Seleccione los sacos desde Inventario Café. Al guardar, la existencia se descuenta automáticamente.</p></div>
  {msg&&<div className="success-box">{msg}</div>}{err&&<div className="error-box">{err}</div>}
  {isAdmin&&<form className="week-form" onSubmit={save} style={card}>
   <div className="section-heading"><div><h2>{editing?'Editar abonada':'Nueva abonada'}</h2><p>Método fijo: manual. Seleccione primero la finca.</p></div></div>
   <div className="week-main-fields"><label>Fecha<input type="date" value={form.application_date} onChange={e=>setForm({...form,application_date:e.target.value})} required/></label><label>Finca<select value={form.farm_id} onChange={e=>setForm({...form,farm_id:e.target.value})} required><option value="">Seleccione finca</option>{activeFarms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Método<input value="Manual" readOnly/></label><label>Área abonada (ha)<input type="number" min="0.001" step="0.001" value={form.treated_area_ha} onChange={e=>setForm({...form,treated_area_ha:e.target.value})}/></label></div>
   {!availableInventory.length&&<div className="error-box">No hay abonos en sacos disponibles en Inventario Café para esta finca. Regístrelos primero en Inventario Café.</div>}
   <h3 style={{marginTop:24}}>Abonos utilizados</h3><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>#</th><th>Abono de inventario</th><th>Sacos disponibles</th><th>Sacos usados</th><th>Precio por saco</th><th>Subtotal</th><th>Acción</th></tr></thead><tbody>{form.products.map((p,i)=>{const inv=inventory.find(x=>String(x.id)===String(p.inventory_id));return <tr key={i}><td>{i+1}</td><td><select value={p.inventory_id} onChange={e=>chooseInventory(i,e.target.value)} required><option value="">Seleccione abono</option>{availableInventory.map(x=><option key={x.id} value={x.id}>{x.product_name}</option>)}</select></td><td>{inv?Number(inv.current_stock).toLocaleString('es-CR'):'—'}</td><td><input type="number" min="0.001" step="0.001" max={inv?Number(inv.current_stock):undefined} value={p.quantity} onChange={e=>setProduct(i,'quantity',e.target.value)} required/></td><td>{money(p.price_per_sack)}</td><td><strong>{money(Number(p.quantity||0)*Number(p.price_per_sack||0))}</strong></td><td>{form.products.length>1?<button type="button" className="secondary-action" onClick={()=>removeProduct(i)}>Quitar</button>:'—'}</td></tr>})}</tbody></table></div>
   <div className="quick-actions" style={{marginTop:12}}><button type="button" className="secondary-action" onClick={addProduct}>＋ Agregar abono</button></div>
   <div className="week-main-fields" style={{marginTop:20}}><label>Responsable<input value={form.responsible} onChange={e=>setForm({...form,responsible:e.target.value})}/></label><label>Observaciones<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>
   <div className="pay-preview"><span>Total de sacos<strong>{form.products.reduce((s,p)=>s+Number(p.quantity||0),0).toFixed(2)}</strong></span><span>Costo total del abono<strong>{money(totalNow)}</strong></span></div>
   <div className="quick-actions"><button type="button" className="secondary-action" onClick={reset}>Limpiar</button><button className="primary-action" disabled={busy||!availableInventory.length}>{editing?'Guardar cambios':'Guardar abonada'}</button></div>
  </form>}
  <div style={{...card,marginTop:20}}><div className="section-heading"><div><h2>Historial de abonadas</h2><p>Solo registros de abonada manual.</p></div></div><div className="week-main-fields"><label>Finca<select value={filterFarm} onChange={e=>setFilterFarm(e.target.value)}><option value="">Todas</option>{activeFarms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><button type="button" className="secondary-action" onClick={()=>setFilterFarm('')}>Limpiar filtro</button></div><div className="pay-preview"><span>Abonadas<strong>{summary.apps}</strong></span><span>Fincas<strong>{summary.farms.size}</strong></span><span>Área abonada<strong>{summary.area.toFixed(2)} ha</strong></span><span>Costo total<strong>{money(summary.cost)}</strong></span></div><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Fecha</th><th>Finca</th><th>Método</th><th>Abonos</th><th>Área</th><th>Costo total</th><th>Costo/ha</th><th>Responsable</th>{isAdmin&&<th>Acción</th>}</tr></thead><tbody>{filtered.length?filtered.map(x=><tr key={x.id}><td>{dateLabel(x.application_date)}</td><td><strong>{x.farm_name}</strong></td><td>Manual</td><td>{x.products||'—'}</td><td>{x.treated_area_ha?`${Number(x.treated_area_ha).toFixed(2)} ha`:'—'}</td><td><strong>{money(x.total_cost)}</strong></td><td>{x.cost_per_ha==null?'—':money(x.cost_per_ha)}</td><td>{x.responsible||'—'}</td>{isAdmin&&<td><button type="button" className="secondary-action" onClick={()=>edit(x)}>Editar</button></td>}</tr>):<tr><td colSpan={isAdmin?9:8} className="empty-cell">No hay registros de abonadas.</td></tr>}</tbody></table></div></div>
 </div>
}
