'use client'
import {useMemo,useState} from'react'
function money(v){return`₡${Number(v||0).toLocaleString('es-CR',{maximumFractionDigits:2})}`}
const months=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre']
export default function CoffeeLaborReports({entries,farms,workers}){
 const years=useMemo(()=>[...new Set(entries.map(x=>String(x.work_date).slice(0,4)))].sort().reverse(),[entries]),[year,setYear]=useState(''),[month,setMonth]=useState(''),[farm,setFarm]=useState(''),[worker,setWorker]=useState('')
 const y=year||years[0]||String(new Date().getFullYear())
 const filtered=useMemo(()=>entries.filter(x=>String(x.work_date).slice(0,4)===y&&(!month||Number(String(x.work_date).slice(5,7))===Number(month))&&(!farm||String(x.farm_id)===farm)&&(!worker||String(x.worker_id)===worker)),[entries,y,month,farm,worker])
 const group=useMemo(()=>{const m=new Map();filtered.forEach(x=>{const k=String(x.farm_id),r=m.get(k)||{farm:x.farm_name,workers:new Set(),days:new Set(),jornal:0,hours:0,extraHours:0,extra:0,total:0};r.workers.add(String(x.worker_id));r.days.add(String(x.work_date));r.jornal+=Number(x.jornal_rate||0);r.hours+=Number(x.hours||0);r.extraHours+=Number(x.overtime_hours||0);r.extra+=Number(x.overtime_hours||0)*Number(x.overtime_rate||0);r.total+=Number(x.amount||0);m.set(k,r)});return[...m.values()]},[filtered])
 const annual=useMemo(()=>months.map((name,i)=>{const a=entries.filter(x=>String(x.work_date).slice(0,4)===y&&Number(String(x.work_date).slice(5,7))===i+1&&(!farm||String(x.farm_id)===farm)&&(!worker||String(x.worker_id)===worker));return{name,workers:new Set(a.map(x=>String(x.worker_id))).size,days:new Set(a.map(x=>String(x.work_date))).size,jornal:a.reduce((s,x)=>s+Number(x.jornal_rate||0),0),extraHours:a.reduce((s,x)=>s+Number(x.overtime_hours||0),0),extra:a.reduce((s,x)=>s+Number(x.overtime_hours||0)*Number(x.overtime_rate||0),0),total:a.reduce((s,x)=>s+Number(x.amount||0),0)}}),[entries,y,farm,worker])
 const totals=group.reduce((a,r)=>({jornal:a.jornal+r.jornal,extraHours:a.extraHours+r.extraHours,extra:a.extra+r.extra,total:a.total+r.total}),{jornal:0,extraHours:0,extra:0,total:0})
 function printReport(){window.print()}
 function csv(){const rows=[['Finca','Peones','Días','Costo jornales','Horas extra','Costo horas extra','Total'],...group.map(r=>[r.farm,r.workers.size,r.days.size,r.jornal,r.extraHours,r.extra,r.total])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`reporte-labores-cafe-${y}${month?'-'+month:''}.csv`;a.click();URL.revokeObjectURL(u)}
 return <section className="labor-report-section" style={{marginTop:30}}><div className="section-heading"><div><h2>4. Reportes mensuales y anuales</h2><p>Costo de mano de obra por finca: jornales, horas normales, horas extra y total.</p></div></div><div className="week-main-fields"><label>Año<select value={y} onChange={e=>setYear(e.target.value)}>{years.length?years.map(v=><option key={v}>{v}</option>):<option>{y}</option>}</select></label><label>Mes<select value={month} onChange={e=>setMonth(e.target.value)}><option value="">Todo el año</option>{months.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></label><label>Finca<select value={farm} onChange={e=>setFarm(e.target.value)}><option value="">Todas las fincas</option>{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Peón<select value={worker} onChange={e=>setWorker(e.target.value)}><option value="">Todos los peones</option>{workers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label><button className="secondary-action" onClick={()=>{setMonth('');setFarm('');setWorker('')}}>Limpiar</button></div><div className="pay-preview labor-kpis"><span>Costo jornales<strong>{money(totals.jornal)}</strong></span><span>Horas extra<strong>{totals.extraHours.toFixed(2)}</strong></span><span>Costo horas extra<strong>{money(totals.extra)}</strong></span><span>Costo total<strong>{money(totals.total)}</strong></span></div><div className="quick-actions"><button className="secondary-action" onClick={csv}>Exportar Excel/CSV</button><button className="secondary-action" onClick={printReport}>PDF / Imprimir</button></div><h3>{month?`Reporte mensual · ${months[Number(month)-1]} ${y}`:`Reporte anual por finca · ${y}`}</h3><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Finca</th><th>Peones</th><th>Días</th><th>Horas normales</th><th>Costo jornales</th><th>Horas extra</th><th>Costo horas extra</th><th>Total</th></tr></thead><tbody>{group.length?group.map(r=><tr key={r.farm}><td><strong>{r.farm}</strong></td><td>{r.workers.size}</td><td>{r.days.size}</td><td>{r.hours.toFixed(2)}</td><td>{money(r.jornal)}</td><td>{r.extraHours.toFixed(2)}</td><td>{money(r.extra)}</td><td><strong>{money(r.total)}</strong></td></tr>):<tr><td colSpan="8" className="empty-cell">No hay datos para el período seleccionado.</td></tr>}</tbody></table></div>{!month&&<><h3>Desglose de los 12 meses · {y}</h3><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Mes</th><th>Peones</th><th>Días</th><th>Jornales</th><th>Horas extra</th><th>Costo extra</th><th>Total</th></tr></thead><tbody>{annual.map(r=><tr key={r.name}><td><strong>{r.name}</strong></td><td>{r.workers}</td><td>{r.days}</td><td>{money(r.jornal)}</td><td>{r.extraHours.toFixed(2)}</td><td>{money(r.extra)}</td><td><strong>{money(r.total)}</strong></td></tr>)}</tbody></table></div></>}</section>
}