'use client'
import {useEffect,useState} from'react'

function clean(v){return String(v??'').replace(/\s+/g,' ').trim()}
function xml(v){return clean(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function html(v){return clean(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function safeName(v,i){const s=clean(v).replace(/[\\/:*?\[\]]/g,' ').slice(0,28);return`${i+1}-${s||'Reporte'}`.slice(0,31)}
function visibleReportTables(){const root=document.querySelector('.coffee-module'),history=document.querySelector('.coffee-history');if(!root||!root.textContent.includes('Nómina semanal consolidada de peones'))return[];const weekly=[...root.querySelectorAll('table')].filter(t=>t.offsetParent!==null),saved=history?[...history.querySelectorAll('table')].filter(t=>t.offsetParent!==null):[];return[...weekly,...saved]}
function titleFor(table,i){if(table.closest('.coffee-history'))return'Historial de medidas registradas';let n=table.parentElement,limit=0;while(n&&limit<5){let p=n.previousElementSibling;while(p){const h=p.matches?.('h2,h3')?p:p.querySelector?.('h2,h3');if(h)return clean(h.textContent);p=p.previousElementSibling}n=n.parentElement;limit++}return`Reporte ${i+1}`}
function tableRows(table){return[...table.querySelectorAll('tr')].map(tr=>[...tr.querySelectorAll('th,td')].map(c=>clean(c.innerText))).filter(r=>r.length)}
function excelCell(v){const raw=clean(v),plain=raw.replace(/₡/g,'').replace(/,/g,''),numeric=/^-?\d+(\.\d+)?$/.test(plain),n=Number(plain);return numeric&&Number.isFinite(n)?`<Cell><Data ss:Type="Number">${n}</Data></Cell>`:`<Cell><Data ss:Type="String">${xml(raw)}</Data></Cell>`}
function selectedFilters(){const root=document.querySelector('.coffee-module');if(!root)return[];const fields=[...root.querySelectorAll('.week-main-fields label')];return fields.map(label=>{const name=clean(label.childNodes?.[0]?.textContent||label.textContent),control=label.querySelector('select,input'),value=control?.tagName==='SELECT'?clean(control.selectedOptions?.[0]?.textContent):clean(control?.value);return{name,value:value||'Todos'}}).filter(x=>x.name)}
function summaryCards(){const root=document.querySelector('.coffee-module');if(!root)return[];return[...root.querySelectorAll('.pay-preview')].flatMap((box,bi)=>[...box.querySelectorAll('span')].map(s=>{const strong=s.querySelector('strong'),value=clean(strong?.textContent),label=clean(s.textContent.replace(strong?.textContent||'',''));return{group:bi===0?'Resumen de filtros':'Resumen de nómina',label,value}})).filter(x=>x.label&&x.value)}
function reportMeta(){return{generated:new Date().toLocaleString('es-CR'),filters:selectedFilters(),summary:summaryCards()}}
function summarySheet(meta){const rows=[['Ganadera San Ramón'],['Reportes de café'],['Generado',meta.generated],[],['Filtros aplicados'],...meta.filters.map(x=>[x.name,x.value]),[],['Totales y resumen'],...meta.summary.map(x=>[x.group,x.label,x.value])];return`<Worksheet ss:Name="Resumen"><Table>${rows.map(r=>`<Row>${r.map(excelCell).join('')}</Row>`).join('')}</Table></Worksheet>`}
function exportExcel(){const tables=visibleReportTables();if(!tables.length)return alert('Abra Café → Pagos semanales para exportar los reportes.');const meta=reportMeta(),sheets=tables.map((t,i)=>{const rows=tableRows(t).map(r=>`<Row>${r.map(excelCell).join('')}</Row>`).join('');return`<Worksheet ss:Name="${xml(safeName(titleFor(t,i),i))}"><Table>${rows}</Table></Worksheet>`}).join('');const book=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><DocumentProperties xmlns="urn:schemas-microsoft-com:office:office"><Title>Ganadera San Ramón - Reportes de café</Title></DocumentProperties>${summarySheet(meta)}${sheets}</Workbook>`,blob=new Blob([book],{type:'application/vnd.ms-excel;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Ganadera_San_Ramon_Reportes_Cafe_${new Date().toISOString().slice(0,10)}.xls`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function metaHtml(meta){const filters=meta.filters.map(x=>`<div><span>${html(x.name)}</span><strong>${html(x.value)}</strong></div>`).join(''),summary=meta.summary.map(x=>`<div><span>${html(x.label)}</span><strong>${html(x.value)}</strong></div>`).join('');return`<div class="filters">${filters}</div><div class="summary">${summary}</div>`}
function exportPDF(){const tables=visibleReportTables();if(!tables.length)return alert('Abra Café → Pagos semanales para exportar los reportes.');const meta=reportMeta(),w=window.open('','_blank','width=1200,height=900');if(!w)return alert('Permita las ventanas emergentes para generar el PDF.');const sections=tables.map((t,i)=>`<section><h2>${html(titleFor(t,i))}</h2>${t.outerHTML}</section>`).join('');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Reportes de café - Ganadera San Ramón</title><style>@page{size:landscape;margin:9mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#17251c;margin:0}header{border-bottom:2px solid #2f5b3b;padding-bottom:12px;margin-bottom:14px}h1{margin:0;font-size:24px}header p{margin:5px 0}h2{margin:20px 0 7px;font-size:16px;border-bottom:1px solid #d7dfd8;padding-bottom:5px}section{page-break-before:auto;margin-bottom:20px}section+section{page-break-before:always}table{width:100%;border-collapse:collapse;font-size:9px}thead{display:table-header-group}tfoot{display:table-row-group}tr{page-break-inside:avoid}th,td{border:1px solid #bfc8c1;padding:4px;text-align:left;vertical-align:top}th{background:#eef6ef;font-weight:700}.filters,.summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px;margin:10px 0}.filters div,.summary div{border:1px solid #d5ddd7;padding:6px;border-radius:4px}.filters span,.summary span{display:block;font-size:9px;color:#66756b}.filters strong,.summary strong{display:block;font-size:11px;margin-top:2px}.actions{margin:0 0 12px;text-align:right}.actions button{padding:8px 12px}.status-pill{border:0;padding:0}.secondary-action,.primary-action,button{font-size:9px}@media print{.actions{display:none}button{display:none}}</style></head><body><div class="actions"><button onclick="window.print()">Imprimir / Guardar como PDF</button></div><header><h1>Ganadera San Ramón</h1><p><strong>Reportes de cosecha y nómina de café</strong></p><small>Generado: ${html(meta.generated)}</small>${metaHtml(meta)}</header>${sections}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)}

export default function CoffeeExportTools(){const[ready,setReady]=useState(false);useEffect(()=>{const check=()=>setReady(visibleReportTables().length>0);check();const root=document.querySelector('.dashboard')||document.body;const o=new MutationObserver(check);o.observe(root,{subtree:true,childList:true,characterData:true});return()=>o.disconnect()},[]);if(!ready)return null;return <section className="farms-module" style={{marginTop:20}}><div className="farms-toolbar"><div><h2>Exportar e imprimir reportes</h2><p className="muted">La exportación respeta los filtros visibles e incluye una hoja/resumen con período, finca, peón y totales de la nómina.</p></div><div className="quick-actions"><button type="button" className="secondary-action" onClick={exportExcel}>Exportar Excel</button><button type="button" className="primary-action" onClick={exportPDF}>Imprimir / PDF</button></div></div></section>}
