'use client'
import {useEffect,useMemo,useState} from 'react'
import CoffeeInventoryReports from './CoffeeInventoryReports'
const blank={name:'',category:'Abono',unit:'sacos',minimum_stock:'',unit_cost:'',supplier:'',lot_number:'',expiration_date:'',notes:''}
const entryBlank={inventory_id:'',quantity:'',unit_cost:'',movement_date:'',supplier:'',notes:''}
function money(v){return`₡${Number(v||0).toLocaleString('es-CR',{maximumFractionDigits:2})}`}
function num(v){return Number(v||0).toLocaleString('es-CR',{maximumFractionDigits:3})}
function d(v){return v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString('es-CR'):'—'}
function exp(v){return v?d(v):'N/A'}
function dt(v){return v?new Date(v).toLocaleString('es-CR',{timeZone:'America/Costa_Rica',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true}):'—'}
function ref(m){if(m.reference_type==='compra')return'Ingreso / compra';if(m.reference_type==='abonada')return`Abonada${m.reference_id?` #${m.reference_id}`:''}`;if(m.reference_type==='atomizacion')return`Atomización${m.reference_id?` #${m.reference_id}`:''}`;return m.reference_label||'—'}
function todayCR(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Costa_Rica',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o=Object.fromEntries(parts.map(x=>[x.type,x.value]));return`${o.year}-${o.month}-${o.day}`}
function daysUntil(v){if(!v)return null;const a=new Date(`${todayCR()}T12:00:00`),b=new Date(`${String(v).slice(0,10)}T12:00:00`);return Math.round((b-a)/86400000)}
function expiryState(v){const days=daysUntil(v);if(days==null)return{level:'none',label:'N/A',days:null};if(days<0)return{level:'expired',label:`Vencido hace ${Math.abs(days)} día${Math.abs(days)===1?'':'s'}`,days};if(days===0)return{level:'urgent',label:'Vence hoy',days};if(days<=30)return{level:'urgent',label:`Vence en ${days} día${days===1?'':'s'}`,days};if(days<=90)return{level:'soon',label:`Vence en ${days} días`,days};return{level:'ok',label:'Vigente',days}}
export default function CoffeeInventory({user}){
 const isAdmin=user?.role==='admin';const[products,setProducts]=useState([]),[movements,setMovements]=useState([]),[form,setForm]=useState(blank),[entry,setEntry]=useState(entryBlank),[editing,setEditing]=useState(null),[tab,setTab]=useState('Todos'),[msg,setMsg]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{setEntry(e=>({...e,movement_date:e.movement_date||todayCR()}));load()},[])
 async function load(){const r=await fetch('/api/coffee-inventory',{cache:'no-store'}),data=await r.json();if(r.ok){setProducts(data.products||[]);setMovements(data.movements||[])}else setErr(data.error||'No se pudo cargar el inventario.')}
 const filtered=useMemo(()=>products.filter(p=>tab==='Todos'||(tab==='Abonos'?p.category==='Abono':p.category==='Atomizacion')),[products,tab]);const entries=useMemo(()=>movements.filter(m=>m.movement_type==='entrada'),[movements]);
 const alerts=useMemo(()=>products.filter(p=>p.active).map(p=>{const ex=expiryState(p.expiration_date),stock=Number(p.current_stock||0),minimum=Number(p.minimum_stock||0),out=stock<=0,low=Boolean(p.low_stock)||stock<=minimum;let priority=0,type='',detail='';if(out){priority=5;type='Sin existencia';detail=`Existencia: ${num(stock)} ${p.unit}`}else if(ex.level==='expired'){priority=5;type='Producto vencido';detail=ex.label}else if(ex.level==='urgent'){priority=4;type='Vencimiento próximo';detail=ex.label}else if(low){priority=3;type='Existencia baja';detail=`Existencia ${num(stock)} ${p.unit} · mínimo ${num(minimum)} ${p.unit}`}else if(ex.level==='soon'){priority=2;type='Vence en 90 días';detail=ex.label}return{...p,priority,type,detail,expiry:ex}}).filter(x=>x.priority>0).sort((a,b)=>b.priority-a.priority||(a.expiry.days??9999)-(b.expiry.days??9999)),[products]);
 const totals=useMemo(()=>products.filter(p=>p.active).reduce((a,p)=>{const ex=expiryState(p.expiration_date);a.value+=Number(p.inventory_value||0);a.low+=p.low_stock?1:0;if(Number(p.current_stock||0)<=0)a.out++;if(ex.level==='expired')a.expired++;if(ex.level==='urgent')a.expiring30++;if(ex.level==='soon')a.expiring90++;if(p.category==='Abono')a.abonos++;if(p.category==='Atomizacion')a.atomizos++;return a},{value:0,low:0,out:0,expired:0,expiring30:0,expiring90:0,abonos:0,atomizos:0}),[products]);const categoryLabel=v=>v==='Atomizacion'?'Atomización':'Abono'
 function reset(){setForm(blank);setEditing(null)}
 async function saveProduct(e){e.preventDefault();setBusy(true);setErr('');setMsg('');try{const r=await fetch('/api/coffee-inventory',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{...form,id:editing.id}:form)}),data=await r.json();if(r.ok){setMsg(editing?'Producto actualizado correctamente.':'Producto creado. Ahora registre cada ingreso por fecha.');reset();await load()}else setErr(data.error||'No se pudo guardar.')}catch{setErr('No se pudo conectar con el servidor.')}finally{setBusy(false)}}
 function editProduct(p){setEditing(p);setForm({name:p.product_name||'',category:p.category||'Abono',unit:p.unit||'sacos',minimum_stock:String(p.minimum_stock||''),unit_cost:String(p.unit_cost||''),supplier:p.supplier||'',lot_number:p.lot_number||'',expiration_date:p.expiration_date?String(p.expiration_date).slice(0,10):'',notes:p.notes||''})}
 async function toggle(p){if(!confirm(`¿${p.active?'Desactivar':'Activar'} ${p.product_name}?`))return;await fetch('/api/coffee-inventory',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:p.id,action:'toggle'})});await load()}
 async function addEntry(e){e.preventDefault();setBusy(true);setErr('');setMsg('');try{const r=await fetch('/api/coffee-inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...entry,action:'entrada'})}),data=await r.json();if(r.ok){setMsg(`Ingreso registrado correctamente con fecha ${d(entry.movement_date)}.`);setEntry({...entryBlank,movement_date:entry.movement_date});await load()}else setErr(data.error||'No se pudo registrar el ingreso.')}catch{setErr('No se pudo conectar con el servidor.')}finally{setBusy(false)}}
 const selected=products.find(p=>String(p.id)===String(entry.inventory_id))
 return <section className="farms-module inventory-module"><div className="farms-toolbar"><div><h2>Inventario Productos de Café</h2><p className="muted">Cada compra o ingreso se registra por fecha. La existencia actual se calcula con las entradas y las salidas por abonadas y atomizaciones.</p></div><div className="farm-count"><strong>{products.filter(p=>p.active).length}</strong><span>productos activos</span></div></div>{msg&&<div className="success-box">{msg}</div>}{err&&<div className="error-box">{err}</div>}<div className="summary-grid"><article className="summary-card"><span>Abonos</span><strong>{totals.abonos}</strong></article><article className="summary-card"><span>Atomización</span><strong>{totals.atomizos}</strong></article><article className="summary-card"><span>Valor inventario</span><strong>{money(totals.value)}</strong></article><article className="summary-card"><span>Existencia baja</span><strong>{totals.low}</strong></article></div>
 <div className="section-heading" style={{marginTop:24}}><div><h3>⚠️ Alertas de inventario</h3><p>Control automático de existencias bajas, productos agotados y vencimientos.</p></div></div><div className="summary-grid"><article className="summary-card"><span>Sin existencia</span><strong>{totals.out}</strong></article><article className="summary-card"><span>Vencidos</span><strong>{totals.expired}</strong></article><article className="summary-card"><span>Vencen ≤ 30 días</span><strong>{totals.expiring30}</strong></article><article className="summary-card"><span>Vencen 31–90 días</span><strong>{totals.expiring90}</strong></article></div><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Prioridad</th><th>Producto</th><th>Lote</th><th>Categoría</th><th>Existencia</th><th>Mínimo</th><th>Vence</th><th>Alerta</th></tr></thead><tbody>{alerts.length?alerts.map(p=><tr key={`alert-${p.id}`}><td><strong>{p.priority>=5?'🔴 Alta':p.priority>=3?'🟠 Media':'🟡 Preventiva'}</strong></td><td><strong>{p.product_name}</strong></td><td>{p.lot_number||'—'}</td><td>{categoryLabel(p.category)}</td><td>{num(p.current_stock)} {p.unit}</td><td>{num(p.minimum_stock)} {p.unit}</td><td>{exp(p.expiration_date)}</td><td><strong>{p.type}</strong><br/><small>{p.detail}</small></td></tr>):<tr><td colSpan="8" className="empty-cell">No hay alertas activas. El inventario está dentro de los parámetros definidos.</td></tr>}</tbody></table></div>
 {isAdmin&&<><h3>{editing?'Editar producto':'Crear producto'}</h3><form className="week-form labor-entry-card" onSubmit={saveProduct}><div className="week-main-fields labor-grid"><label>Nombre del producto<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Categoría<select value={form.category} onChange={e=>setForm({...form,category:e.target.value,unit:e.target.value==='Abono'?'sacos':'L'})}><option value="Abono">Abono</option><option value="Atomizacion">Atomización</option></select></label><label>Unidad<select value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}>{form.category==='Abono'?<><option>sacos</option><option>kg</option><option>unidades</option></>:<><option>L</option><option>ml</option><option>kg</option><option>unidades</option></>}</select></label><label>Existencia mínima<input type="number" step="0.001" min="0" value={form.minimum_stock} onChange={e=>setForm({...form,minimum_stock:e.target.value})}/></label><label>Costo de referencia<input type="number" step="0.01" min="0" value={form.unit_cost} onChange={e=>setForm({...form,unit_cost:e.target.value})}/></label><label>Proveedor habitual<input value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})}/></label><label>Lote<input value={form.lot_number} onChange={e=>setForm({...form,lot_number:e.target.value})}/></label><label>Vencimiento (opcional)<input type="date" value={form.expiration_date} onChange={e=>setForm({...form,expiration_date:e.target.value})}/><small>Si no aplica, déjelo vacío. Se mostrará como N/A.</small></label><label>Observaciones<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="success-box">Crear el producto no aumenta la existencia. Cada cantidad se agrega desde “Registrar ingreso por fecha”.</div><div style={{display:'flex',gap:10}}><button className="primary-action" disabled={busy}>{busy?'Guardando…':editing?'Guardar cambios':'Crear producto'}</button>{editing&&<button type="button" className="secondary-action" onClick={reset}>Cancelar</button>}</div></form>
 <h3>Registrar ingreso por fecha</h3><form className="week-form labor-entry-card" onSubmit={addEntry}><div className="week-main-fields labor-grid"><label>Fecha de ingreso<input type="date" value={entry.movement_date} onChange={e=>setEntry({...entry,movement_date:e.target.value})} required/></label><label>Producto<select value={entry.inventory_id} onChange={e=>{const p=products.find(x=>String(x.id)===e.target.value);setEntry({...entry,inventory_id:e.target.value,unit_cost:p?.unit_cost||'',supplier:p?.supplier||''})}} required><option value="">Seleccione</option>{products.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.product_name} · Lote {p.lot_number||'s/l'} · {categoryLabel(p.category)} · {p.unit}</option>)}</select></label><label>Cantidad {selected?`(${selected.unit})`:''}<input type="number" step="0.001" min="0.001" value={entry.quantity} onChange={e=>setEntry({...entry,quantity:e.target.value})} required/></label><label>Costo unitario<input type="number" step="0.01" min="0" value={entry.unit_cost} onChange={e=>setEntry({...entry,unit_cost:e.target.value})}/></label><label>Proveedor<input value={entry.supplier} onChange={e=>setEntry({...entry,supplier:e.target.value})}/></label><label>Observación<input value={entry.notes} onChange={e=>setEntry({...entry,notes:e.target.value})}/></label></div><button className="primary-action" disabled={busy}>{busy?'Registrando…':'Guardar ingreso'}</button></form></>}
 <div className="section-heading" style={{marginTop:24}}><div><h3>Ingresos por fecha</h3><p>Registro completo de fecha de compra, hora del sistema, lote y usuario responsable.</p></div></div><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Fecha de ingreso</th><th>Registrado</th><th>Usuario</th><th>Producto</th><th>Lote</th><th>Vence</th><th>Cantidad</th><th>Costo unit.</th><th>Proveedor</th><th>Observación</th></tr></thead><tbody>{entries.length?entries.map(m=><tr key={m.id}><td><strong>{d(m.movement_date)}</strong></td><td>{dt(m.created_at)}</td><td><strong>{m.created_by_name||'Usuario'}</strong></td><td>{m.product_name}</td><td>{m.lot_number||'—'}</td><td>{exp(m.expiration_date)}</td><td>{num(m.quantity)} {m.unit}</td><td>{money(m.unit_cost)}</td><td>{m.supplier||'—'}</td><td>{m.notes||'—'}</td></tr>):<tr><td colSpan="10" className="empty-cell">Aún no hay ingresos registrados.</td></tr>}</tbody></table></div>
 <div className="section-heading" style={{marginTop:24}}><div><h3>Existencias actuales</h3><p>El saldo se actualiza con cada ingreso y con cada consumo registrado.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{['Todos','Abonos','Atomización'].map(t=><button key={t} className={tab===t?'primary-action':'secondary-action'} onClick={()=>setTab(t)}>{t}</button>)}</div></div><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Producto</th><th>Categoría</th><th>Alcance</th><th>Existencia</th><th>Mínimo</th><th>Costo ref.</th><th>Valor</th><th>Lote</th><th>Vence</th><th>Estado</th>{isAdmin&&<th>Acciones</th>}</tr></thead><tbody>{filtered.length?filtered.map(p=>{const ex=expiryState(p.expiration_date);const bad=Number(p.current_stock||0)<=0||p.low_stock||ex.level==='expired'||ex.level==='urgent';return <tr key={p.id}><td><strong>{p.product_name}</strong><br/><small>{p.supplier||''}</small></td><td>{categoryLabel(p.category)}</td><td><strong>Todas las fincas</strong></td><td><strong>{num(p.current_stock)} {p.unit}</strong></td><td>{num(p.minimum_stock)} {p.unit}</td><td>{money(p.unit_cost)}</td><td>{money(p.inventory_value)}</td><td>{p.lot_number||'—'}</td><td>{exp(p.expiration_date)}<br/><small>{ex.label}</small></td><td><span className={`status-pill ${bad?'inactive':'active'}`}>{Number(p.current_stock||0)<=0?'Sin existencia':ex.level==='expired'?'Vencido':ex.level==='urgent'?'Vence pronto':p.low_stock?'Existencia baja':'Disponible'}</span></td>{isAdmin&&<td><button onClick={()=>editProduct(p)}>Editar</button> <button onClick={()=>toggle(p)}>{p.active?'Desactivar':'Activar'}</button></td>}</tr>}):<tr><td colSpan={isAdmin?11:10} className="empty-cell">Aún no hay productos registrados.</td></tr>}</tbody></table></div>
 <h3 style={{marginTop:24}}>Historial general de movimientos</h3><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Fecha</th><th>Registrado</th><th>Usuario</th><th>Producto / lote</th><th>Tipo</th><th>Referencia</th><th>Cantidad</th><th>Finca</th><th>Proveedor</th><th>Observación</th></tr></thead><tbody>{movements.length?movements.map(m=><tr key={m.id}><td>{d(m.movement_date)}</td><td>{dt(m.created_at)}</td><td><strong>{m.created_by_name||'Usuario'}</strong></td><td><strong>{m.product_name}</strong><br/><small>Lote: {m.lot_number||'—'} · Vence: {exp(m.expiration_date)}</small></td><td>{m.movement_type}</td><td><strong>{ref(m)}</strong></td><td>{num(m.quantity)} {m.unit}</td><td>{m.movement_type==='salida'?(m.farm_name||'—'):'Inventario general'}</td><td>{m.supplier||'—'}</td><td>{m.notes||'—'}</td></tr>):<tr><td colSpan="10" className="empty-cell">Aún no hay movimientos.</td></tr>}</tbody></table></div>
 <CoffeeInventoryReports products={products} movements={movements}/>
 </section>
}
