'use client'
import {useEffect,useMemo,useState} from'react'
import CoffeeLaborReports from './CoffeeLaborReports'

const workerBlank={full_name:'',identification:'',phone:''}
const entryBlank={work_date:'',worker_id:'',farm_id:'',task:'',pay_mode:'Jornal',hours:'',rate:'',jornal_rate:'',overtime_hours:'',overtime_rate:'',notes:''}
function money(v){return`₡${Number(v||0).toLocaleString('es-CR',{maximumFractionDigits:2})}`}
function d(v){return v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString('es-CR'):'—'}
function dt(v){return v?new Date(v).toLocaleString('es-CR',{dateStyle:'short',timeStyle:'short'}):'—'}
function weekEnd(v){if(!v)return'';const x=new Date(`${v}T12:00:00Z`);x.setUTCDate(x.getUTCDate()+6);return x.toISOString().slice(0,10)}
function weekLabel(v){return v?`${d(v)} – ${d(weekEnd(v))}`:'Todas las semanas'}

export default function CoffeeLaborWorkers({farms,user}){
 const isAdmin=user?.role==='admin',activeFarms=useMemo(()=>farms.filter(f=>f.active),[farms])
 const[workers,setWorkers]=useState([]),[entries,setEntries]=useState([]),[payroll,setPayroll]=useState([]),[farmSummary,setFarmSummary]=useState([])
 const[workerForm,setWorkerForm]=useState(workerBlank),[editingWorker,setEditingWorker]=useState(null),[entryForm,setEntryForm]=useState(entryBlank),[editingEntry,setEditingEntry]=useState(null)
 const[filterWeek,setFilterWeek]=useState(''),[filterFarm,setFilterFarm]=useState(''),[filterWorker,setFilterWorker]=useState(''),[msg,setMsg]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{const today=new Date().toISOString().slice(0,10);setEntryForm(f=>({...f,work_date:f.work_date||today}));loadAll()},[])
 async function loadAll(){const[wr,lr]=await Promise.all([fetch('/api/coffee-labor-workers',{cache:'no-store'}),fetch('/api/coffee-labor',{cache:'no-store'})]);const[wd,ld]=await Promise.all([wr.json(),lr.json()]);if(wr.ok)setWorkers(wd.workers||[]);if(lr.ok){setEntries(ld.entries||[]);setPayroll(ld.payroll||[]);setFarmSummary(ld.farm_summary||[])}else setErr(ld.error||'No se pudo cargar la planilla.')}
 const activeWorkers=useMemo(()=>workers.filter(w=>w.active),[workers]),weeks=useMemo(()=>[...new Set(entries.map(x=>String(x.week_start).slice(0,10)))].sort().reverse(),[entries])
 const filteredEntries=useMemo(()=>entries.filter(x=>(!filterWeek||String(x.week_start).slice(0,10)===filterWeek)&&(!filterFarm||String(x.farm_id)===filterFarm)&&(!filterWorker||String(x.worker_id)===filterWorker)),[entries,filterWeek,filterFarm,filterWorker])
 const filteredPayroll=useMemo(()=>payroll.filter(x=>(!filterWeek||String(x.week_start).slice(0,10)===filterWeek)&&(!filterWorker||String(x.worker_id)===filterWorker)),[payroll,filterWeek,filterWorker])
 const filteredFarms=useMemo(()=>farmSummary.filter(x=>(!filterWeek||String(x.week_start).slice(0,10)===filterWeek)&&(!filterFarm||String(x.farm_id)===filterFarm)),[farmSummary,filterWeek,filterFarm])
 const totals=useMemo(()=>filteredEntries.reduce((a,x)=>{a.amount+=Number(x.amount||0);a.hours+=Number(x.hours||0);a.overtime+=Number(x.overtime_hours||0);a.jornal+=Number(x.jornal_rate||0);a.overtimeCost+=Number(x.overtime_amount||0);a.workers.add(String(x.worker_id));a.farms.add(String(x.farm_id));return a},{amount:0,hours:0,overtime:0,jornal:0,overtimeCost:0,workers:new Set(),farms:new Set()}),[filteredEntries])
 async function saveWorker(e){e.preventDefault();setBusy(true);const r=await fetch('/api/coffee-labor-workers',{method:editingWorker?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...workerForm,id:editingWorker?.id,active:editingWorker?editingWorker.active:true})}),data=await r.json();if(r.ok){setWorkerForm(workerBlank);setEditingWorker(null);setMsg('Peón guardado correctamente.');await loadAll()}else setErr(data.error);setBusy(false)}
 function editWorker(w){setEditingWorker(w);setWorkerForm({full_name:w.full_name,identification:w.identification||'',phone:w.phone||''})}
 async function toggleWorker(w){await fetch('/api/coffee-labor-workers',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...w,active:!w.active})});await loadAll()}
 async function saveEntry(e){e.preventDefault();setBusy(true);const r=await fetch('/api/coffee-labor',{method:editingEntry?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...entryForm,id:editingEntry?.id})}),data=await r.json();if(r.ok){const keep=entryForm.work_date;setEntryForm({...entryBlank,work_date:keep});setEditingEntry(null);setMsg(`Labor guardada. Total: ${money(data.amount)}.`);await loadAll()}else setErr(data.error);setBusy(false)}
 function editEntry(x){setEditingEntry(x);setEntryForm({work_date:String(x.work_date).slice(0,10),worker_id:String(x.worker_id),farm_id:String(x.farm_id),task:x.task||'',pay_mode:x.pay_mode||'Jornal',hours:x.hours==null?'':String(x.hours),rate:String(x.rate||''),jornal_rate:String(x.jornal_rate||''),overtime_hours:String(x.overtime_hours||''),overtime_rate:String(x.overtime_rate||''),notes:x.notes||''})}
 async function setPaid(x,paid){if(!confirm(`¿Marcar a ${x.worker_name} como ${paid?'PAGADO':'PENDIENTE'}?`))return;await fetch('/api/coffee-labor',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'payment',worker_id:x.worker_id,week_start:String(x.week_start).slice(0,10),paid})});await loadAll()}
 function printReceipt(x){const w=window.open('','_blank');if(!w)return;w.document.write(`<h1>Ganadera San Ramón</h1><h2>Comprobante labores café</h2><p><b>Peón:</b> ${x.worker_name}</p><p><b>Semana:</b> ${weekLabel(String(x.week_start).slice(0,10))}</p><p><b>Fincas:</b> ${x.farms_worked}</p><p><b>Jornales:</b> ${money(x.total_jornal)}</p><p><b>Horas extra:</b> ${Number(x.total_overtime_hours||0).toFixed(2)} · ${money(x.total_overtime)}</p><h2>Total: ${money(x.total_amount)}</h2><p>Fecha pago: ${dt(x.paid_at)}</p><button onclick="print()">Imprimir</button>`);w.document.close()}
 const basePreview=entryForm.pay_mode==='Horas'?Number(entryForm.hours||0)*Number(entryForm.rate||0):Number(entryForm.jornal_rate||0),overtimePreview=Number(entryForm.overtime_hours||0)*Number(entryForm.overtime_rate||0)
 return <div className="labor-module"><div className="section-heading"><div><h2>Peones de labores de café</h2><p>Control de jornales, horas, horas extra, fincas y pagos.</p></div></div>{msg&&<div className="success-box">{msg}</div>}{err&&<div className="error-box">{err}</div>}<div className="labor-banner"><strong>👷 Mano de obra de café</strong><span>Separada de los recolectores.</span></div>
 <h3>1. Registro de peones de labores</h3>{isAdmin&&<form className="worker-form" onSubmit={saveWorker}><input placeholder="Nombre completo" value={workerForm.full_name} onChange={e=>setWorkerForm({...workerForm,full_name:e.target.value})} required/><input placeholder="Identificación" value={workerForm.identification} onChange={e=>setWorkerForm({...workerForm,identification:e.target.value})}/><input placeholder="Teléfono" value={workerForm.phone} onChange={e=>setWorkerForm({...workerForm,phone:e.target.value})}/><button className="primary-action">{editingWorker?'Guardar cambios':'Agregar peón'}</button></form>}<div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Peón</th><th>Identificación</th><th>Teléfono</th><th>Estado</th>{isAdmin&&<th>Acción</th>}</tr></thead><tbody>{workers.map(w=><tr key={w.id}><td><strong>{w.full_name}</strong></td><td>{w.identification||'—'}</td><td>{w.phone||'—'}</td><td>{w.active?'Activo':'Inactivo'}</td>{isAdmin&&<td><button onClick={()=>editWorker(w)}>Editar</button> <button onClick={()=>toggleWorker(w)}>{w.active?'Desactivar':'Activar'}</button></td>}</tr>)}</tbody></table></div>
 <h3>2. Planilla diaria de la semana</h3>{isAdmin&&<form className="week-form labor-entry-card" onSubmit={saveEntry}><div className="week-main-fields labor-grid"><label>Fecha<input type="date" value={entryForm.work_date} onChange={e=>setEntryForm({...entryForm,work_date:e.target.value})} required/></label><label>Peón<select value={entryForm.worker_id} onChange={e=>setEntryForm({...entryForm,worker_id:e.target.value})} required><option value="">Seleccione</option>{activeWorkers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label><label>Finca<select value={entryForm.farm_id} onChange={e=>setEntryForm({...entryForm,farm_id:e.target.value})} required><option value="">Seleccione</option>{activeFarms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Labor<input value={entryForm.task} onChange={e=>setEntryForm({...entryForm,task:e.target.value})} required/></label><label>Forma pago<select value={entryForm.pay_mode} onChange={e=>setEntryForm({...entryForm,pay_mode:e.target.value})}><option>Jornal</option><option>Horas</option></select></label>{entryForm.pay_mode==='Jornal'?<label>Valor jornal<input type="number" value={entryForm.jornal_rate} onChange={e=>setEntryForm({...entryForm,jornal_rate:e.target.value})} required/></label>:<><label>Horas normales<input type="number" step=".25" value={entryForm.hours} onChange={e=>setEntryForm({...entryForm,hours:e.target.value})} required/></label><label>Costo hora normal<input type="number" value={entryForm.rate} onChange={e=>setEntryForm({...entryForm,rate:e.target.value})} required/></label></>}<label>Horas extra<input type="number" step=".25" value={entryForm.overtime_hours} onChange={e=>setEntryForm({...entryForm,overtime_hours:e.target.value})}/></label><label>Costo hora extra<input type="number" value={entryForm.overtime_rate} onChange={e=>setEntryForm({...entryForm,overtime_rate:e.target.value})}/></label><label>Observación<input value={entryForm.notes} onChange={e=>setEntryForm({...entryForm,notes:e.target.value})}/></label></div><div className="pay-preview"><span>Costo base<strong>{money(basePreview)}</strong></span><span>Horas extra<strong>{money(overtimePreview)}</strong></span><span>Total día<strong>{money(basePreview+overtimePreview)}</strong></span></div><button className="primary-action">{editingEntry?'Guardar corrección':'Registrar día trabajado'}</button></form>}
 <h3>3. Control semanal</h3><div className="week-main-fields"><label>Semana<select value={filterWeek} onChange={e=>setFilterWeek(e.target.value)}><option value="">Todas</option>{weeks.map(w=><option key={w} value={w}>{weekLabel(w)}</option>)}</select></label><label>Finca<select value={filterFarm} onChange={e=>setFilterFarm(e.target.value)}><option value="">Todas</option>{activeFarms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Peón<select value={filterWorker} onChange={e=>setFilterWorker(e.target.value)}><option value="">Todos</option>{workers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label></div><div className="pay-preview labor-kpis"><span>Total<strong>{money(totals.amount)}</strong></span><span>Jornales<strong>{money(totals.jornal)}</strong></span><span>Horas normales<strong>{totals.hours.toFixed(2)}</strong></span><span>Horas extra<strong>{totals.overtime.toFixed(2)}</strong></span><span>Costo extra<strong>{money(totals.overtimeCost)}</strong></span></div>
 <h3>Detalle diario</h3><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Fecha</th><th>Peón</th><th>Finca</th><th>Labor</th><th>Jornal</th><th>Horas</th><th>H. extra</th><th>₡ H. extra</th><th>Total</th>{isAdmin&&<th>Acción</th>}</tr></thead><tbody>{filteredEntries.map(x=><tr key={x.id}><td>{d(x.work_date)}</td><td>{x.worker_name}</td><td>{x.farm_name}</td><td>{x.task}</td><td>{money(x.jornal_rate)}</td><td>{Number(x.hours||0).toFixed(2)}</td><td>{Number(x.overtime_hours||0).toFixed(2)}</td><td>{money(x.overtime_amount)}</td><td><strong>{money(x.amount)}</strong></td>{isAdmin&&<td><button onClick={()=>editEntry(x)}>Editar</button></td>}</tr>)}</tbody></table></div>
 <h3>Costo semanal por finca</h3><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Semana</th><th>Finca</th><th>Peones</th><th>Horas</th><th>H. extra</th><th>Total</th></tr></thead><tbody>{filteredFarms.map(x=><tr key={`${x.week_start}-${x.farm_id}`}><td>{weekLabel(String(x.week_start).slice(0,10))}</td><td>{x.farm_name}</td><td>{x.workers}</td><td>{Number(x.total_hours||0).toFixed(2)}</td><td>{Number(x.total_overtime_hours||0).toFixed(2)}</td><td><strong>{money(x.total_amount)}</strong></td></tr>)}</tbody></table></div>
 <h3>Nómina semanal y registro de pago</h3><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Semana</th><th>Peón</th><th>Fincas</th><th>Días</th><th>Jornales</th><th>H. extra</th><th>Total</th><th>Estado</th><th>Comprobante</th>{isAdmin&&<th>Acción</th>}</tr></thead><tbody>{filteredPayroll.map(x=><tr key={`${x.week_start}-${x.worker_id}`}><td>{weekLabel(String(x.week_start).slice(0,10))}</td><td>{x.worker_name}</td><td>{x.farms_worked}</td><td>{x.days_worked}</td><td>{money(x.total_jornal)}</td><td>{money(x.total_overtime)}</td><td><strong>{money(x.total_amount)}</strong></td><td>{x.paid?'Pagado':'Pendiente'}</td><td>{x.paid?<button onClick={()=>printReceipt(x)}>Imprimir</button>:'—'}</td>{isAdmin&&<td><button onClick={()=>setPaid(x,!x.paid)}>{x.paid?'Marcar pendiente':'Registrar pago'}</button></td>}</tr>)}</tbody></table></div>
 <CoffeeLaborReports entries={entries} farms={activeFarms} workers={workers}/></div>
}