'use client'
import {useEffect,useMemo,useState} from'react'

const workerBlank={full_name:'',identification:'',phone:''}
const entryBlank={work_date:'',worker_id:'',farm_id:'',task:'',pay_mode:'Jornal',hours:'',rate:'',jornal_rate:'',overtime_hours:'',overtime_rate:'',notes:''}
function money(v){return`₡${Number(v||0).toLocaleString('es-CR',{maximumFractionDigits:2})}`}
function d(v){return v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString('es-CR'):'—'}
function dt(v){return v?new Date(v).toLocaleString('es-CR',{dateStyle:'short',timeStyle:'short'}):'—'}
function weekEnd(v){if(!v)return'';const x=new Date(`${v}T12:00:00Z`);x.setUTCDate(x.getUTCDate()+6);return x.toISOString().slice(0,10)}
function weekLabel(v){return v?`${d(v)} – ${d(weekEnd(v))}`:'Todas las semanas'}

export default function CoffeeLaborWorkers({farms,user}){
 const isAdmin=user?.role==='admin',activeFarms=useMemo(()=>farms.filter(f=>f.active),[farms])
 const[workers,setWorkers]=useState([]),[entries,setEntries]=useState([]),[payroll,setPayroll]=useState([]),[farmSummary,setFarmSummary]=useState([])
 const[workerForm,setWorkerForm]=useState(workerBlank),[editingWorker,setEditingWorker]=useState(null),[entryForm,setEntryForm]=useState(entryBlank),[editingEntry,setEditingEntry]=useState(null)
 const[filterWeek,setFilterWeek]=useState(''),[filterFarm,setFilterFarm]=useState(''),[filterWorker,setFilterWorker]=useState('')
 const[msg,setMsg]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{const today=new Date().toISOString().slice(0,10);setEntryForm(f=>({...f,work_date:f.work_date||today}));loadAll()},[])
 async function loadAll(){const [wr,lr]=await Promise.all([fetch('/api/coffee-labor-workers',{cache:'no-store'}),fetch('/api/coffee-labor',{cache:'no-store'})]);const [wd,ld]=await Promise.all([wr.json(),lr.json()]);if(wr.ok)setWorkers(wd.workers||[]);else setErr(wd.error||'No se pudieron cargar los peones.');if(lr.ok){setEntries(ld.entries||[]);setPayroll(ld.payroll||[]);setFarmSummary(ld.farm_summary||[])}else setErr(ld.error||'No se pudo cargar la planilla.')}
 const activeWorkers=useMemo(()=>workers.filter(w=>w.active),[workers])
 const weeks=useMemo(()=>[...new Set(entries.map(x=>String(x.week_start).slice(0,10)))].sort().reverse(),[entries])
 const filteredEntries=useMemo(()=>entries.filter(x=>(!filterWeek||String(x.week_start).slice(0,10)===filterWeek)&&(!filterFarm||String(x.farm_id)===filterFarm)&&(!filterWorker||String(x.worker_id)===filterWorker)),[entries,filterWeek,filterFarm,filterWorker])
 const filteredPayroll=useMemo(()=>payroll.filter(x=>(!filterWeek||String(x.week_start).slice(0,10)===filterWeek)&&(!filterWorker||String(x.worker_id)===filterWorker)),[payroll,filterWeek,filterWorker])
 const filteredFarms=useMemo(()=>farmSummary.filter(x=>(!filterWeek||String(x.week_start).slice(0,10)===filterWeek)&&(!filterFarm||String(x.farm_id)===filterFarm)),[farmSummary,filterWeek,filterFarm])
 const totals=useMemo(()=>filteredEntries.reduce((a,x)=>{a.amount+=Number(x.amount||0);a.hours+=Number(x.hours||0);a.overtime+=Number(x.overtime_hours||0);a.jornal+=Number(x.jornal_rate||0);a.overtimeCost+=Number(x.overtime_amount||0);a.days.add(String(x.work_date));a.workers.add(String(x.worker_id));a.farms.add(String(x.farm_id));return a},{amount:0,hours:0,overtime:0,jornal:0,overtimeCost:0,days:new Set(),workers:new Set(),farms:new Set()}),[filteredEntries])
 async function saveWorker(e){e.preventDefault();setBusy(true);setErr('');setMsg('');try{const body={...workerForm,id:editingWorker?.id,active:editingWorker?editingWorker.active:true};const r=await fetch('/api/coffee-labor-workers',{method:editingWorker?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await r.json();if(!r.ok){setErr(data.error||'No se pudo guardar el peón.');return}setWorkerForm(workerBlank);setEditingWorker(null);setMsg('Peón de labores guardado correctamente.');await loadAll()}finally{setBusy(false)}}
 function editWorker(w){setEditingWorker(w);setWorkerForm({full_name:w.full_name,identification:w.identification||'',phone:w.phone||''})}
 async function toggleWorker(w){setBusy(true);await fetch('/api/coffee-labor-workers',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...w,active:!w.active})});await loadAll();setBusy(false)}
 async function saveEntry(e){e.preventDefault();setBusy(true);setErr('');setMsg('');try{const body={...entryForm,id:editingEntry?.id};const r=await fetch('/api/coffee-labor',{method:editingEntry?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await r.json();if(!r.ok){setErr(data.error||'No se pudo guardar la labor.');return}const keepDate=entryForm.work_date;setEntryForm({...entryBlank,work_date:keepDate});setEditingEntry(null);setMsg(`Labor guardada. Costo del día: ${money(data.amount)}.`);await loadAll()}finally{setBusy(false)}}
 function editEntry(x){setEditingEntry(x);setEntryForm({work_date:String(x.work_date).slice(0,10),worker_id:String(x.worker_id),farm_id:String(x.farm_id),task:x.task||'',pay_mode:x.pay_mode||'Jornal',hours:x.hours==null?'':String(x.hours),rate:String(x.rate||''),jornal_rate:String(x.jornal_rate||''),overtime_hours:String(x.overtime_hours||''),overtime_rate:String(x.overtime_rate||''),notes:x.notes||''})}
 async function setPaid(x,paid){if(!window.confirm(`¿Marcar a ${x.worker_name} como ${paid?'PAGADO':'PENDIENTE'} para la semana ${weekLabel(String(x.week_start).slice(0,10))}?`))return;setBusy(true);setErr('');try{const r=await fetch('/api/coffee-labor',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'payment',worker_id:x.worker_id,week_start:String(x.week_start).slice(0,10),paid})}),data=await r.json();if(!r.ok){setErr(data.error||'No se pudo actualizar el pago.');return}setMsg(`${x.worker_name}: ${paid?'pago registrado':'pago marcado pendiente'}.`);await loadAll()}finally{setBusy(false)}}
 function printReceipt(x){const w=window.open('','_blank','width=800,height=850');if(!w)return;w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Comprobante labores café</title><style>body{font-family:Arial;margin:40px;color:#17351f}.box{max-width:700px;margin:auto;border:1px solid #ccd8ce;border-radius:16px;padding:30px}h1{margin:0}table{width:100%;border-collapse:collapse;margin:24px 0}td{padding:10px;border-bottom:1px solid #e5ebe6}.total{font-size:24px;font-weight:800;padding:16px;background:#f2f7f2}.sign{display:grid;grid-template-columns:1fr 1fr;gap:50px;margin-top:70px}.line{border-top:1px solid #222;text-align:center;padding-top:8px}@media print{button{display:none}}</style></head><body><button onclick="print()">Imprimir</button><div class="box"><h1>Ganadera San Ramón</h1><p>Comprobante semanal · Peón de labores de café</p><table><tr><td>Peón</td><td><b>${x.worker_name}</b></td></tr><tr><td>Semana</td><td>${weekLabel(String(x.week_start).slice(0,10))}</td></tr><tr><td>Fincas trabajadas</td><td>${x.farms_worked||'—'}</td></tr><tr><td>Días trabajados</td><td>${x.days_worked}</td></tr><tr><td>Horas normales</td><td>${Number(x.total_hours||0).toFixed(2)}</td></tr><tr><td>Horas extra</td><td>${Number(x.total_overtime_hours||0).toFixed(2)}</td></tr><tr><td>Total jornales</td><td>${money(x.total_jornal)}</td></tr><tr><td>Total horas extra</td><td>${money(x.total_overtime)}</td></tr><tr><td>Fecha de pago</td><td>${dt(x.paid_at)}</td></tr></table><div class="total">Total pagado: ${money(x.total_amount)}</div><div class="sign"><div class="line">Firma del peón</div><div class="line">Firma del responsable</div></div></div></body></html>`);w.document.close()}
 const basePreview=entryForm.pay_mode==='Horas'?Number(entryForm.hours||0)*Number(entryForm.rate||0):Number(entryForm.jornal_rate||0)
 const overtimePreview=Number(entryForm.overtime_hours||0)*Number(entryForm.overtime_rate||0)
 const preview=basePreview+overtimePreview
 return <div className="labor-module">
  <div className="section-heading"><div><h2>Peones de labores de café</h2><p>Registro independiente de los recolectores. Controle jornales, horas normales, horas extra, finca por día y pagos semanales.</p></div></div>
  {msg&&<div className="success-box">{msg}</div>}{err&&<div className="error-box">{err}</div>}
  <div className="labor-banner"><strong>👷 Mano de obra de café</strong><span>Jornal + horas extra, todo separado de los recolectores.</span></div>
  <h3>1. Registro de peones de labores</h3>
  {isAdmin&&<form className="worker-form" onSubmit={saveWorker}><input placeholder="Nombre completo" value={workerForm.full_name} onChange={e=>setWorkerForm({...workerForm,full_name:e.target.value})} required/><input placeholder="Identificación" value={workerForm.identification} onChange={e=>setWorkerForm({...workerForm,identification:e.target.value})}/><input placeholder="Teléfono" value={workerForm.phone} onChange={e=>setWorkerForm({...workerForm,phone:e.target.value})}/><button className="primary-action" disabled={busy}>{editingWorker?'Guardar cambios':'Agregar peón'}</button>{editingWorker&&<button type="button" className="secondary-action" onClick={()=>{setEditingWorker(null);setWorkerForm(workerBlank)}}>Cancelar</button>}</form>}
  <div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Peón</th><th>Identificación</th><th>Teléfono</th><th>Estado</th>{isAdmin&&<th>Acciones</th>}</tr></thead><tbody>{workers.length?workers.map(w=><tr key={w.id}><td><strong>{w.full_name}</strong></td><td>{w.identification||'—'}</td><td>{w.phone||'—'}</td><td><span className={`status-pill ${w.active?'active':'inactive'}`}>{w.active?'Activo':'Inactivo'}</span></td>{isAdmin&&<td><button className="mini-action" onClick={()=>editWorker(w)}>Editar</button> <button className="mini-action" disabled={busy} onClick={()=>toggleWorker(w)}>{w.active?'Desactivar':'Activar'}</button></td>}</tr>):<tr><td colSpan={isAdmin?5:4} className="empty-cell">Aún no hay peones de labores registrados.</td></tr>}</tbody></table></div>
  <h3>2. Planilla diaria de la semana</h3>
  {isAdmin&&<form className="week-form labor-entry-card" onSubmit={saveEntry}><div className="week-main-fields labor-grid"><label>Fecha<input type="date" value={entryForm.work_date} onChange={e=>setEntryForm({...entryForm,work_date:e.target.value})} required/></label><label>Peón<select value={entryForm.worker_id} onChange={e=>setEntryForm({...entryForm,worker_id:e.target.value})} required><option value="">Seleccione peón</option>{activeWorkers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label><label>Finca<select value={entryForm.farm_id} onChange={e=>setEntryForm({...entryForm,farm_id:e.target.value})} required><option value="">Seleccione finca</option>{activeFarms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Labor realizada<input placeholder="Ej. poda, limpia, deshija, mantenimiento" value={entryForm.task} onChange={e=>setEntryForm({...entryForm,task:e.target.value})} required/></label><label>Forma de pago<select value={entryForm.pay_mode} onChange={e=>setEntryForm({...entryForm,pay_mode:e.target.value,hours:e.target.value==='Jornal'?'':entryForm.hours})}><option>Jornal</option><option>Horas</option></select></label>{entryForm.pay_mode==='Horas'&&<><label>Horas normales<input type="number" min="0.25" step="0.25" value={entryForm.hours} onChange={e=>setEntryForm({...entryForm,hours:e.target.value})} required/></label><label>Costo hora normal<input type="number" min="0" step="0.01" value={entryForm.rate} onChange={e=>setEntryForm({...entryForm,rate:e.target.value})} required/></label></>} {entryForm.pay_mode==='Jornal'&&<label>Valor del jornal<input type="number" min="0" step="0.01" value={entryForm.jornal_rate} onChange={e=>setEntryForm({...entryForm,jornal_rate:e.target.value})} required/></label>}<label>Horas extra<input type="number" min="0" step="0.25" value={entryForm.overtime_hours} onChange={e=>setEntryForm({...entryForm,overtime_hours:e.target.value})}/></label><label>Costo por hora extra<input type="number" min="0" step="0.01" value={entryForm.overtime_rate} onChange={e=>setEntryForm({...entryForm,overtime_rate:e.target.value})}/></label><label>Observación<input value={entryForm.notes} onChange={e=>setEntryForm({...entryForm,notes:e.target.value})}/></label></div><div className="pay-preview"><span>Costo base<strong>{money(basePreview)}</strong></span><span>Costo horas extra<strong>{money(overtimePreview)}</strong></span><span>Total del día<strong>{money(preview)}</strong></span></div><div className="labor-save-row"><button className="primary-action" disabled={busy}>{editingEntry?'Guardar corrección':'Registrar día trabajado'}</button>{editingEntry&&<button type="button" className="secondary-action" onClick={()=>{setEditingEntry(null);setEntryForm({...entryBlank,work_date:entryForm.work_date})}}>Cancelar</button>}</div></form>}
  <h3>3. Control semanal</h3><div className="week-main-fields"><label>Semana<select value={filterWeek} onChange={e=>setFilterWeek(e.target.value)}><option value="">Todas las semanas</option>{weeks.map(w=><option key={w} value={w}>{weekLabel(w)}</option>)}</select></label><label>Finca<select value={filterFarm} onChange={e=>setFilterFarm(e.target.value)}><option value="">Todas las fincas</option>{activeFarms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Peón<select value={filterWorker} onChange={e=>setFilterWorker(e.target.value)}><option value="">Todos los peones</option>{workers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label><button className="secondary-action" type="button" onClick={()=>{setFilterWeek('');setFilterFarm('');setFilterWorker('')}}>Limpiar filtros</button></div>
  <div className="pay-preview labor-kpis"><span>Costo mano de obra<strong>{money(totals.amount)}</strong></span><span>Jornales<strong>{money(totals.jornal)}</strong></span><span>Horas normales<strong>{totals.hours.toFixed(2)}</strong></span><span>Horas extra<strong>{totals.overtime.toFixed(2)}</strong></span><span>Costo horas extra<strong>{money(totals.overtimeCost)}</strong></span></div>
  <h3>Detalle diario: dónde trabajó cada peón</h3><div className="farms-table-wrap"><table className="farms-table weekly-table"><thead><tr><th>Fecha</th><th>Peón</th><th>Finca</th><th>Labor</th><th>Pago</th><th>Horas normales</th><th>Jornal</th><th>Horas extra</th><th>₡ hora extra</th><th>Costo extra</th><th>Total día</th><th>Observación</th>{isAdmin&&<th>Acción</th>}</tr></thead><tbody>{filteredEntries.length?filteredEntries.map(x=><tr key={x.id}><td>{d(x.work_date)}</td><td><strong>{x.worker_name}</strong></td><td>{x.farm_name}</td><td>{x.task}</td><td>{x.pay_mode}</td><td>{x.hours==null?'—':Number(x.hours).toFixed(2)}</td><td>{money(x.jornal_rate)}</td><td>{Number(x.overtime_hours||0).toFixed(2)}</td><td>{money(x.overtime_rate)}</td><td>{money(x.overtime_amount)}</td><td><strong>{money(x.amount)}</strong></td><td>{x.notes||'—'}</td>{isAdmin&&<td><button className="mini-action" onClick={()=>editEntry(x)}>Editar</button></td>}</tr>):<tr><td colSpan={isAdmin?13:12} className="empty-cell">No hay labores para estos filtros.</td></tr>}</tbody></table></div>
  <h3>Costo semanal por finca</h3><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Semana</th><th>Finca</th><th>Peones</th><th>Días</th><th>Horas normales</th><th>Horas extra</th><th>Jornales</th><th>Costo horas extra</th><th>Costo total</th></tr></thead><tbody>{filteredFarms.length?filteredFarms.map((x,i)=><tr key={i}><td>{weekLabel(String(x.week_start).slice(0,10))}</td><td><strong>{x.farm_name}</strong></td><td>{x.workers}</td><td>{x.work_days}</td><td>{Number(x.total_hours||0).toFixed(2)}</td><td>{Number(x.total_overtime_hours||0).toFixed(2)}</td><td>{money(x.total_jornal)}</td><td>{money(x.total_overtime)}</td><td><strong>{money(x.total_amount)}</strong></td></tr>):<tr><td colSpan="9" className="empty-cell">No hay costos por finca para estos filtros.</td></tr>}</tbody></table></div>
  <h3>Nómina semanal y registro de pago</h3><div className="farms-table-wrap"><table className="farms-table weekly-table"><thead><tr><th>Semana</th><th>Peón</th><th>Fincas trabajadas</th><th>Días</th><th>Horas normales</th><th>Horas extra</th><th>Jornales</th><th>Horas extra ₡</th><th>Total a pagar</th><th>Estado</th><th>Fecha pago</th><th>Comprobante</th>{isAdmin&&<th>Acción</th>}</tr></thead><tbody>{filteredPayroll.length?filteredPayroll.map(x=><tr key={`${x.week_start}-${x.worker_id}`}><td>{weekLabel(String(x.week_start).slice(0,10))}</td><td><strong>{x.worker_name}</strong></td><td>{x.farms_worked}</td><td>{x.days_worked}</td><td>{Number(x.total_hours||0).toFixed(2)}</td><td>{Number(x.total_overtime_hours||0).toFixed(2)}</td><td>{money(x.total_jornal)}</td><td>{money(x.total_overtime)}</td><td><strong>{money(x.total_amount)}</strong></td><td><span className={`status-pill ${x.paid?'active':'inactive'}`}>{x.paid?'Pagado':'Pendiente'}</span></td><td>{x.paid?dt(x.paid_at):'—'}</td><td>{x.paid?<button className="secondary-action" type="button" onClick={()=>printReceipt(x)}>Imprimir</button>:'—'}</td>{isAdmin&&<td><button className="secondary-action" type="button" disabled={busy} onClick={()=>setPaid(x,!x.paid)}>{x.paid?'Marcar pendiente':'Registrar pago'}</button></td>}</tr>):<tr><td colSpan={isAdmin?13:12} className="empty-cell">No hay nómina semanal registrada.</td></tr>}</tbody></table></div>
 </div>
}
