'use client'
import {useEffect,useState} from'react'

function clean(v){return String(v??'').replace(/\s+/g,' ').trim()}
function xml(v){return clean(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function safeName(v,i){const s=clean(v).replace(/[\\/:*?\[\]]/g,' ').slice(0,28);return`${i+1}-${s||'Reporte'}`.slice(0,31)}
function visibleReportTables(){const root=document.querySelector('.coffee-module');if(!root||!root.textContent.includes('Nómina semanal consolidada de peones'))return[];return[...root.querySelectorAll('table')].filter(t=>t.offsetParent!==null)}
function titleFor(table,i){let n=table.parentElement,limit=0;while(n&&limit<5){let p=n.previousElementSibling;while(p){const h=p.matches?.('h2,h3')?p:p.querySelector?.('h2,h3');if(h)return clean(h.textContent);p=p.previousElementSibling}n=n.parentElement;limit++}return`Reporte ${i+1}`}
function tableRows(table){return[...table.querySelectorAll('tr')].map(tr=>[...tr.querySelectorAll('th,td')].map(c=>clean(c.innerText))).filter(r=>r.length)}
function excelCell(v){const n=Number(String(v).replace(/[^0-9.-]/g,'')),numeric=/^-?\d+(\.\d+)?$/.test(String(v).replace(/,/g,''));return numeric&&Number.isFinite(n)?`<Cell><Data ss:Type="Number">${n}</Data></Cell>`:`<Cell><Data ss:Type="String">${xml(v)}</Data></Cell>`}
function exportExcel(){const tables=visibleReportTables();if(!tables.length)return alert('Abra Café → Pagos semanales para exportar los reportes.');const sheets=tables.map((t,i)=>{const rows=tableRows(t).map(r=>`<Row>${r.map(excelCell).join('')}</Row>`).join('');return`<Worksheet ss:Name="${xml(safeName(titleFor(t,i),i))}"><Table>${rows}</Table></Worksheet>`}).join('');const book=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><DocumentProperties xmlns="urn:schemas-microsoft-com:office:office"><Title>Ganadera San Ramón - Reportes de café</Title></DocumentProperties>${sheets}</Workbook>`,blob=new Blob([book],{type:'application/vnd.ms-excel;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Ganadera_San_Ramon_Reportes_Cafe_${new Date().toISOString().slice(0,10)}.xls`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportPDF(){const tables=visibleReportTables();if(!tables.length)return alert('Abra Café → Pagos semanales para exportar los reportes.');const w=window.open('','_blank','width=1100,height=850');if(!w)return alert('Permita las ventanas emergentes para generar el PDF.');const sections=tables.map((t,i)=>`<section><h2>${xml(titleFor(t,i))}</h2>${t.outerHTML}</section>`).join('');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Reportes de café - Ganadera San Ramón</title><style>@page{size:landscape;margin:10mm}body{font-family:Arial,sans-serif;color:#17251c}header{margin-bottom:20px}h1{margin:0}h2{margin:24px 0 8px;font-size:16px}section{page-break-inside:avoid;margin-bottom:24px}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border:1px solid #bbb;padding:5px;text-align:left}th{background:#eef6ef}.actions{margin-bottom:16px}@media print{.actions{display:none}}</style></head><body><div class="actions"><button onclick="window.print()">Imprimir / Guardar como PDF</button></div><header><h1>Ganadera San Ramón</h1><p>Reportes semanales de cosecha y nómina de café</p><small>Generado: ${new Date().toLocaleString('es-CR')}</small></header>${sections}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)}

export default function CoffeeExportTools(){const[ready,setReady]=useState(false);useEffect(()=>{const check=()=>setReady(visibleReportTables().length>0);check();const root=document.querySelector('.coffee-module');if(!root)return;const o=new MutationObserver(check);o.observe(root,{subtree:true,childList:true,characterData:true});return()=>o.disconnect()},[]);if(!ready)return null;return <section className="farms-module" style={{marginTop:20}}><div className="farms-toolbar"><div><h2>Exportar reportes</h2><p className="muted">Descargue la nómina y los cuatro reportes semanales respetando los filtros seleccionados.</p></div><div className="quick-actions"><button type="button" className="secondary-action" onClick={exportExcel}>Exportar Excel</button><button type="button" className="primary-action" onClick={exportPDF}>Exportar PDF</button></div></div></section>}
