'use client'
import {useEffect,useMemo,useState} from'react'

const sections=['Peones de café','Cosecha diaria','Pagos semanales','Fertilización','Aplicaciones','Abonos','Gastos de café','Producción por finca','Reportes de café']
const blankWorker={full_name:'',identification:'',phone:''}
function money(v){return`₡${Number(v||0).toLocaleString('es-CR',{maximumFractionDigits:2})}`}
function dateLabel(v){return v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString('es-CR',{weekday:'short',day:'2-digit',month:'2-digit'}):'—'}
function paidDateLabel(v){return v?new Date(v).toLocaleString('es-CR',{dateStyle:'short',timeStyle:'short'}):'—'}
function week(d){const x=new Date(`${d}T12:00:00`);x.setDate(x.getDate()+3-(x.getDay()+6)%7);const w=new Date(x.getFullYear(),0,4);return 1+Math.round(((x-w)/86400000-3+(w.getDay()+6)%7)/7)}
function mondayUtc(v){const x=new Date(`${String(v).slice(0,10)}T12:00:00Z`),d=(x.getUTCDay()+6)%7;x.setUTCDate(x.getUTCDate()-d);return x}
function seasonForDate(date,seasons){const d=String(date||'').slice(0,10);return[...seasons].filter(s=>String(s.start_date).slice(0,10)<=d).sort((a,b)=>String(b.start_date).localeCompare(String(a.start_date)))[0]||null}
function harvestWeekForDate(date,seasons){const s=seasonForDate(date,seasons);if(!s)return null;const n=Math.floor((mondayUtc(date)-mondayUtc(s.start_date))/604800000)+1;return n>0?n:null}
function shortPeriodDate(d){return d.toLocaleDateString('es-CR',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).replace(/\./g,'')}
function weekPeriod(date){const start=mondayUtc(date),end=new Date(start);end.setUTCDate(end.getUTCDate()+6);return`${shortPeriodDate(start)} – ${shortPeriodDate(end)}`}
function weekLabel(w,y,date,seasons){const n=harvestWeekForDate(date,seasons),period=weekPeriod(date);return`Semana ${w} / ${y}${n?` · Semana de cosecha ${n}`:' · Cosecha sin iniciar'} · ${period}`}
function blankMeasure(rate='',farm=''){return{farm_id:farm,quantity:'',rate,notes:''}}
function measureNumber(x){const n=Number(x?.measure_number);if(n>0)return n;const m=String(x?.notes||x||'').match(/Medida\s+(\d+)/i);return Number(m?.[1]||1)}
function receiptNumber(x){return`CAF-${x.year}-${String(x.week_number).padStart(2,'0')}-${String(x.worker_id).padStart(4,'0')}`}
function printReceipt(x){const win=window.open('','_blank','width=850,height=900');if(!win)return;win.document.write(`<html><body><h1>Ganadera San Ramón</h1><h2>Comprobante de pago de cosecha de café</h2><p><strong>Peón:</strong> ${x.worker_name}</p><p><strong>Semana:</strong> ${weekLabel(x.week_number,x.year,x.date,x.seasons||[])}</p><p><strong>Fincas:</strong> ${x.farms||'—'}</p><p><strong>Cajuelas:</strong> ${Number(x.cajuelas).toFixed(2)}</p><p><strong>Total pagado:</strong> ${money(x.total)}</p><p><strong>Fecha de pago:</strong> ${paidDateLabel(x.paid_at)}</p><button onclick="window.print()">Imprimir / Guardar PDF</button></body></html>`);win.document.close();win.focus()}

export default function CoffeeModule({farms,user}){
 const isAdmin=user?.role==='admin',activeFarms=useMemo(()=>farms.filter(f=>f.active),[farms])
 const[section,setSection]=useState('Peones de café'),[workers,setWorkers]=useState([]),[harvest,setHarvest]=useState([]),[seasons,setSeasons]=useState([])
 const[workerForm,setWorkerForm]=useState(blankWorker),[editingWorker,setEditingWorker]=useState(null)
 const[harvestDate,setHarvestDate]=useState(''),[defaultFarm,setDefaultFarm]=useState(''),[generalRate,setGeneralRate]=useState(''),[dailyRows,setDailyRows]=useState({})
 const[payWeek,setPayWeek]=useState(''),[payFarm,setPayFarm]=useState(''),[payWorker,setPayWorker]=useState('')
 const[msg,setMsg]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false)
 const activeWorkers=useMemo(()=>workers.filter(w=>w.active),[workers])
 useEffect(()=>{loadWorkers();loadHarvest();loadSeasons()},[])
 async function loadWorkers(){const r=await fetch('/api/workers',{cache:'no-store'}),d=await r.json();if(r.ok)setWorkers(d.workers||[])}
 async function loadHarvest(){const r=await fetch('/api/coffee-harvest',{cache:'no-store'}),d=await r.json();if(r.ok)setHarvest(d.harvest||[])}
 async function loadSeasons(){const r=await fetch('/api/coffee-seasons',{cache:'no-store'}),d=await r.json();if(r.ok)setSeasons(d.seasons||[])}
 async function saveWorker(e){e.preventDefault();setBusy(true);const p={...workerForm,id:editingWorker?.id,active:editingWorker?editingWorker.active:true},r=await fetch('/api/workers',{method:editingWorker?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}),d=await r.json();if(r.ok){setWorkerForm(blankWorker);setEditingWorker(null);setMsg('Peón guardado correctamente.');await loadWorkers()}else setErr(d.error);setBusy(false)}
 async function toggleWorker(w){await fetch('/api/workers',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...w,active:!w.active})});loadWorkers()}
 function measuresFor(id){return dailyRows[id]||[blankMeasure(generalRate,defaultFarm)]}
 function setMeasure(id,i,k,v){setDailyRows(r=>{const a=[...(r[id]||[blankMeasure(generalRate,defaultFarm)])];a[i]={...a[i],[k]:v};return{...r,[id]:a}})}
 function addMeasure(id){setDailyRows(r=>({...r,[id]:[...(r[id]||[blankMeasure(generalRate,defaultFarm)]),blankMeasure(generalRate,defaultFarm)]}))}
 async function saveDaily(e){e.preventDefault();setBusy(true);setErr('');try{const entries=[];activeWorkers.forEach(w=>measuresFor(w.id).forEach((m,i)=>{if(Number(m.quantity)>0)entries.push({worker_id:w.id,farm_id:m.farm_id||defaultFarm,quantity:m.quantity,rate_per_unit:m.rate!==''?m.rate:(generalRate||0),measure_number:i+1,notes:m.notes?`Medida ${i+1}: ${m.notes}`:`Medida ${i+1}`})}));if(entries.some(x=>!x.farm_id)){setErr('Seleccione la finca para cada medida.');return}const r=await fetch('/api/coffee-harvest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({harvest_date:harvestDate,week_number:week(harvestDate),entries})}),d=await r.json();if(!r.ok){setErr(d.error);return}setMsg(`Se registraron ${d.count} medida(s).`);setDailyRows({});await loadHarvest()}finally{setBusy(false)}}
 async function setPayrollPaid(x,paid){const action=paid?'marcar como PAGADO':'devolver a PENDIENTE';const ok=window.confirm(`¿Confirma que desea ${action} el pago de ${x.worker_name}?\n\n${weekLabel(x.week_number,x.year,x.date,seasons)}\nTotal: ${money(x.total)}\n\nEste cambio afectará todas las medidas del peón correspondientes a esta semana.`);if(!ok)return;setBusy(true);setErr('');setMsg('');try{const r=await fetch('/api/coffee-harvest',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({worker_id:x.worker_id,week_number:x.week_number,year:x.year,paid})}),d=await r.json();if(!r.ok){setErr(d.error||'No se pudo actualizar el pago.');return}setMsg(`${x.worker_name}: pago marcado como ${paid?'Pagado':'Pendiente'}.`);await loadHarvest()}finally{setBusy(false)}}
 const paymentWeeks=useMemo(()=>{const m=new Map();harvest.forEach(x=>{const date=String(x.harvest_date).slice(0,10),year=date.slice(0,4),key=`${year}-${x.week_number}`;if(!m.has(key))m.set(key,{key,year,week_number:x.week_number,date})});return[...m.values()]},[harvest])
 const filteredHarvest=useMemo(()=>harvest.filter(x=>{const y=String(x.harvest_date).slice(0,4);return(!payWeek||`${y}-${x.week_number}`===payWeek)&&(!payFarm||String(x.farm_id)===String(payFarm))&&(!payWorker||String(x.worker_id)===String(payWorker))}),[harvest,payWeek,payFarm,payWorker])
 function group(rows,kind){const m={};rows.forEach(x=>{const date=String(x.harvest_date).slice(0,10),year=date.slice(0,4),measure=measureNumber(x),parts=kind==='daily'?[x.week_number,year,x.farm_id,x.worker_id,date,measure]:kind==='farm'?[x.week_number,year,x.farm_id]:[x.week_number,year,x.worker_id],k=parts.join('-');if(!m[k])m[k]={week_number:x.week_number,year,date,farm_name:x.farm_name,worker_id:x.worker_id,worker_name:x.worker_name,measure,cajuelas:0,total:0,days:new Set(),farms:new Set()};m[k].cajuelas+=Number(x.quantity||0);m[k].total+=Number(x.amount||0);m[k].days.add(date);m[k].farms.add(x.farm_name)});return Object.values(m).map(x=>({...x,days:x.days.size,farms:[...x.farms].join(', ')}))}
 const weeklyPayroll=useMemo(()=>group(harvest.filter(x=>{const y=String(x.harvest_date).slice(0,4);return(!payWeek||`${y}-${x.week_number}`===payWeek)&&(!payWorker||String(x.worker_id)===String(payWorker))}),'worker').map(x=>{const source=harvest.filter(h=>String(h.worker_id)===String(x.worker_id)&&Number(h.week_number)===Number(x.week_number)&&String(h.harvest_date).slice(0,4)===String(x.year));return{...x,measures:source.length,paid:source.length>0&&source.every(h=>h.paid),paid_at:source.find(h=>h.paid_at)?.paid_at,seasons}}),[harvest,payWeek,payWorker,seasons])
 const WL=x=>weekLabel(x.week_number,x.year,x.date,seasons)
 return <section className="coffee-module"><div className="subnav">{sections.map(s=><button key={s} className={section===s?'active':''} onClick={()=>setSection(s)}>{s}</button>)}</div>{msg&&<div className="success-box">{msg}</div>}{err&&<div className="error-box">{err}</div>}
 {section==='Peones de café'?<><h2>Peones de café</h2>{isAdmin&&<form className="worker-form" onSubmit={saveWorker}><input placeholder="Nombre completo" value={workerForm.full_name} onChange={e=>setWorkerForm({...workerForm,full_name:e.target.value})} required/><input placeholder="Identificación" value={workerForm.identification} onChange={e=>setWorkerForm({...workerForm,identification:e.target.value})}/><input placeholder="Teléfono" value={workerForm.phone} onChange={e=>setWorkerForm({...workerForm,phone:e.target.value})}/><button className="primary-action">Agregar peón</button></form>}<div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Peón</th><th>Identificación</th><th>Teléfono</th><th>Estado</th></tr></thead><tbody>{workers.map(w=><tr key={w.id}><td>{w.full_name}</td><td>{w.identification||'—'}</td><td>{w.phone||'—'}</td><td>{w.active?'Activo':'Inactivo'}</td></tr>)}</tbody></table></div></>:
 section==='Cosecha diaria'?<><h2>Planilla de cosecha diaria</h2>{isAdmin&&<form onSubmit={saveDaily}><div className="week-main-fields"><label>Fecha<input type="date" value={harvestDate} onChange={e=>setHarvestDate(e.target.value)} required/></label><label>Finca predeterminada<select value={defaultFarm} onChange={e=>setDefaultFarm(e.target.value)}><option value="">Seleccione</option>{activeFarms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Precio general<input type="number" value={generalRate} onChange={e=>setGeneralRate(e.target.value)}/></label></div><table className="farms-table"><thead><tr><th>Peón</th><th>Medidas</th></tr></thead><tbody>{activeWorkers.map(w=><tr key={w.id}><td>{w.full_name}</td><td>{measuresFor(w.id).map((m,i)=><div className="measure-row" key={i}><span>Medida {i+1}</span><select value={m.farm_id||defaultFarm} onChange={e=>setMeasure(w.id,i,'farm_id',e.target.value)}>{activeFarms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><input type="number" placeholder="Cajuelas" value={m.quantity} onChange={e=>setMeasure(w.id,i,'quantity',e.target.value)}/><input type="number" placeholder="₡/cajuela" value={m.rate!==''?m.rate:generalRate} onChange={e=>setMeasure(w.id,i,'rate',e.target.value)}/><input placeholder="Observación" value={m.notes} onChange={e=>setMeasure(w.id,i,'notes',e.target.value)}/></div>)}<button type="button" onClick={()=>addMeasure(w.id)}>+ Agregar medida</button></td></tr>)}</tbody></table><button className="primary-action" disabled={busy}>Guardar todas las medidas</button></form>}</>:
 section==='Pagos semanales'?<><h2>Pagos semanales</h2><div className="week-main-fields"><label>Semana<select value={payWeek} onChange={e=>setPayWeek(e.target.value)}><option value="">Todas las semanas</option>{paymentWeeks.map(x=><option key={x.key} value={x.key}>{WL(x)}</option>)}</select></label><label>Finca<select value={payFarm} onChange={e=>setPayFarm(e.target.value)}><option value="">Todas</option>{activeFarms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Peón<select value={payWorker} onChange={e=>setPayWorker(e.target.value)}><option value="">Todos</option>{workers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label></div><h2>Nómina semanal consolidada de peones</h2><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Semana y período</th><th>Peón</th><th>Fincas</th><th>Días</th><th>Medidas</th><th>Cajuelas</th><th>Total</th><th>Estado</th><th>Fecha pago</th><th>Comprobante</th>{isAdmin&&<th>Acción</th>}</tr></thead><tbody>{weeklyPayroll.map(x=><tr key={`${x.year}-${x.week_number}-${x.worker_id}`}><td>{WL(x)}</td><td><strong>{x.worker_name}</strong></td><td>{x.farms}</td><td>{x.days}</td><td>{x.measures}</td><td>{x.cajuelas.toFixed(2)}</td><td>{money(x.total)}</td><td>{x.paid?'Pagado':'Pendiente'}</td><td>{x.paid?paidDateLabel(x.paid_at):'—'}</td><td>{x.paid?<button onClick={()=>printReceipt(x)}>Comprobante</button>:'—'}</td>{isAdmin&&<td><button type="button" disabled={busy} onClick={()=>setPayrollPaid(x,!x.paid)}>{x.paid?'Marcar pendiente':'Marcar pagado'}</button></td>}</tr>)}</tbody></table></div><h2>Detalle diario</h2><div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Semana</th><th>Finca</th><th>Peón</th><th>Día</th><th>Medida</th><th>Cajuelas</th><th>Pago</th></tr></thead><tbody>{group(filteredHarvest,'daily').map((x,i)=><tr key={i}><td>{WL(x)}</td><td>{x.farm_name}</td><td>{x.worker_name}</td><td>{dateLabel(x.date)}</td><td>Medida {x.measure}</td><td>{x.cajuelas.toFixed(2)}</td><td>{money(x.total)}</td></tr>)}</tbody></table></div></>:
 <div className="section-heading"><div><h2>{section}</h2><p>Este módulo se conectará con las fincas registradas y sus reportes.</p></div></div>}
 </section>
}