'use client'
import {useEffect,useMemo,useState} from'react'
import CoffeeModule from './CoffeeModule'

const modules=[{name:'Café',icon:'☕',detail:'Cosecha, peones, pagos y aplicaciones.'},{name:'Ganado',icon:'🐄',detail:'Animales, lotes, tratamientos y control sanitario.'},{name:'Inventario Café',icon:'📦',detail:'Fertilizantes, abonos, agroquímicos y herramientas.'},{name:'Inventario Ganado',icon:'💉',detail:'Medicamentos, vacunas, alimentos y materiales.'},{name:'Gastos',icon:'₡',detail:'Registro y consulta de gastos por finca y actividad.'},{name:'Reportes',icon:'📊',detail:'Resumen semanal, mensual y anual.'},{name:'Fincas',icon:'🌿',detail:'Administración de las fincas registradas.'},{name:'Usuarios',icon:'👥',detail:'Administradores y usuarios de consulta.',adminOnly:true}]

function CoffeeSeasonControl({user}){
 const isAdmin=user?.role==='admin',[seasons,setSeasons]=useState([]),[date,setDate]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState('')
 useEffect(()=>{load()},[])
 async function load(){const r=await fetch('/api/coffee-seasons',{cache:'no-store'}),d=await r.json();if(r.ok){setSeasons(d.seasons||[]);const s=(d.seasons||[])[0];if(s)setDate(String(s.start_date).slice(0,10))}}
 async function save(){if(!date)return;setBusy(true);setMsg('');setErr('');try{const r=await fetch('/api/coffee-seasons',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({start_date:date})}),d=await r.json();if(!r.ok){setErr(d.error||'No se pudo guardar el inicio de cosecha.');return}setMsg(`Temporada ${d.year}: semana anual ${d.start_week} definida como Semana de cosecha 1.`);await load()}finally{setBusy(false)}}
 const current=seasons[0]
 return <section className="farms-module" style={{marginBottom:20}}><div className="farms-toolbar"><div><h2>Temporada de cosecha</h2><p className="muted">Defina cuándo inicia la cosecha. Esa semana anual será la Semana de cosecha 1 y las siguientes continuarán 2, 3, 4…</p></div>{current&&<div className="farm-count"><strong>{current.start_week}</strong><span>semana anual inicial</span></div>}</div>{current&&<div className="success-box">Temporada {current.year}: inicia el {new Date(`${String(current.start_date).slice(0,10)}T12:00:00`).toLocaleDateString('es-CR')} · Semana anual {current.start_week} = Semana de cosecha 1.</div>}{isAdmin&&<div className="farm-form"><div><label>{current?'Corregir fecha de inicio':'Fecha de inicio de cosecha'}</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><button type="button" className="primary-action" disabled={busy||!date} onClick={save}>{busy?'Guardando…':current?'Guardar corrección':'Iniciar cosecha'}</button></div>}{msg&&<div className="success-box">{msg}</div>}{err&&<div className="error-box">{err}</div>}</section>
}

export default function Home(){
 const[loading,setLoading]=useState(true),[user,setUser]=useState(null),[farms,setFarms]=useState([]),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authError,setAuthError]=useState(''),[busy,setBusy]=useState(false),[activeModule,setActiveModule]=useState('Inicio')
 const[farmName,setFarmName]=useState(''),[editingFarm,setEditingFarm]=useState(null),[farmError,setFarmError]=useState(''),[farmMessage,setFarmMessage]=useState(''),[farmBusy,setFarmBusy]=useState(false)
 const isAdmin=user?.role==='admin',visibleModules=useMemo(()=>modules.filter(x=>!x.adminOnly||isAdmin),[isAdmin]),activeFarms=useMemo(()=>farms.filter(f=>f.active),[farms])
 useEffect(()=>{init()},[])
 async function init(){try{const r=await fetch('/api/auth/session',{cache:'no-store'}),d=await r.json();if(d.user){setUser(d.user);await loadFarms()}}finally{setLoading(false)}}
 async function loadFarms(){const r=await fetch('/api/farms',{cache:'no-store'});if(r.ok){const d=await r.json();setFarms(d.farms||[])}}
 async function login(e){e.preventDefault();setBusy(true);setAuthError('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})}),d=await r.json();if(!r.ok){setAuthError(d.error||'No se pudo iniciar sesión.');return}setUser(d.user);setPassword('');await loadFarms()}catch{setAuthError('No se pudo conectar con el servidor.')}finally{setBusy(false)}}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});setUser(null);setFarms([]);setActiveModule('Inicio')}
 async function saveFarm(e){e.preventDefault();setFarmBusy(true);setFarmError('');setFarmMessage('');try{const r=await fetch('/api/farms',{method:editingFarm?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editingFarm?{id:editingFarm.id,name:farmName,active:editingFarm.active}:{name:farmName})}),d=await r.json();if(!r.ok){setFarmError(d.error||'No se pudo guardar la finca.');return}setFarmName('');setEditingFarm(null);setFarmMessage(editingFarm?'Finca actualizada correctamente.':'Finca creada correctamente.');await loadFarms()}finally{setFarmBusy(false)}}
 async function toggleFarm(f){setFarmBusy(true);setFarmError('');const r=await fetch('/api/farms',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:f.id,name:f.name,active:!f.active})});if(r.ok)await loadFarms();else{const d=await r.json();setFarmError(d.error||'No se pudo actualizar la finca.')}setFarmBusy(false)}
 if(loading)return <div className="loading-screen">Cargando Ganadera San Ramón…</div>
 if(!user)return <main className="login-page"><section className="brand-panel"><div><p className="eyebrow light">Sistema de gestión agropecuaria</p><h1>Ganadera<br/>San Ramón</h1><p>Administración separada de café y ganado, con inventarios, gastos y reportes por finca.</p></div></section><section className="login-panel"><form className="login-card" onSubmit={login}><span className="logo-mark">GSR</span><h2>Iniciar sesión</h2><p className="muted">Ingrese con su correo y contraseña.</p><label>Correo electrónico</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><label>Contraseña</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/>{authError&&<div className="error-box">{authError}</div>}<button className="primary-button" disabled={busy}>{busy?'Ingresando…':'Ingresar'}</button><p className="login-note">Acceso protegido mediante Neon PostgreSQL y sesión segura.</p></form></section></main>
 return <div className="app-shell"><aside className="sidebar"><div><div className="sidebar-brand"><span>GSR</span><strong>Ganadera<br/>San Ramón</strong></div><nav><button className={`nav-item ${activeModule==='Inicio'?'active':''}`} onClick={()=>setActiveModule('Inicio')}>⌂ <span>Inicio</span></button>{visibleModules.map(i=><button className={`nav-item ${activeModule===i.name?'active':''}`} key={i.name} onClick={()=>setActiveModule(i.name)}>{i.icon} <span>{i.name}</span></button>)}</nav></div><button className="logout" onClick={logout}>Cerrar sesión</button></aside><main className="dashboard"><header className="topbar"><div><p className="eyebrow">{activeModule==='Inicio'?'Panel principal':`Módulo ${activeModule}`}</p><h1>{activeModule==='Inicio'?`Bienvenido${user.full_name?`, ${user.full_name}`:''}`:activeModule}</h1></div><div className="user-badge"><span className={`role ${isAdmin?'admin':'viewer'}`}>{isAdmin?'Administrador':'Consulta'}</span><small>{user.email}</small></div></header>
 {activeModule==='Inicio'?<><section className="summary-grid"><article className="summary-card"><span>Fincas activas</span><strong>{activeFarms.length}</strong></article><article className="summary-card"><span>Área Café</span><strong>Activa</strong></article><article className="summary-card"><span>Área Ganado</span><strong>Activa</strong></article><article className="summary-card"><span>Acceso</span><strong>{isAdmin?'Completo':'Lectura'}</strong></article></section><section className="section-heading"><div><h2>Módulos</h2><p>Seleccione el área que desea gestionar o consultar.</p></div></section><section className="module-grid">{visibleModules.map(i=><article className="module-card" key={i.name}><div className="module-icon">{i.icon}</div><h3>{i.name}</h3><p>{i.detail}</p><button onClick={()=>setActiveModule(i.name)}>Entrar →</button></article>)}</section></>:
 activeModule==='Fincas'?<section className="farms-module"><div className="farms-toolbar"><div><h2>Administración de fincas</h2><p className="muted">Las fincas son la base para café, ganado, inventarios, gastos y reportes.</p></div><div className="farm-count"><strong>{activeFarms.length}</strong><span>activas</span></div></div>{isAdmin&&<form className="farm-form" onSubmit={saveFarm}><div><label>{editingFarm?'Editar nombre':'Nueva finca'}</label><input value={farmName} onChange={e=>setFarmName(e.target.value)} placeholder="Ej. Finca San Ramón" required/></div><button className="primary-action" disabled={farmBusy}>{farmBusy?'Guardando…':editingFarm?'Guardar cambios':'Agregar finca'}</button>{editingFarm&&<button type="button" className="secondary-action" onClick={()=>{setEditingFarm(null);setFarmName('')}}>Cancelar</button>}</form>}{farmError&&<div className="error-box">{farmError}</div>}{farmMessage&&<div className="success-box">{farmMessage}</div>}<div className="farms-table-wrap"><table className="farms-table"><thead><tr><th>Finca</th><th>Estado</th><th>Creada</th>{isAdmin&&<th>Acciones</th>}</tr></thead><tbody>{farms.length?farms.map(f=><tr key={f.id}><td><strong>{f.name}</strong></td><td><span className={`status-pill ${f.active?'active':'inactive'}`}>{f.active?'Activa':'Inactiva'}</span></td><td>{f.created_at?new Date(f.created_at).toLocaleDateString('es-CR'):'—'}</td>{isAdmin&&<td className="farm-actions"><button onClick={()=>{setEditingFarm(f);setFarmName(f.name)}}>Editar</button><button disabled={farmBusy} onClick={()=>toggleFarm(f)}>{f.active?'Desactivar':'Activar'}</button></td>}</tr>):<tr><td colSpan={isAdmin?4:3} className="empty-cell">Aún no hay fincas registradas.</td></tr>}</tbody></table></div></section>:
 activeModule==='Café'?<><CoffeeSeasonControl user={user}/><CoffeeModule farms={farms} user={user}/></>:
 <section className="placeholder-panel"><h2>{activeModule}</h2><p>Continuaremos conectando sus formularios y reportes.</p></section>}</main></div>
}