import {NextResponse} from'next/server'
import {sql} from'../../../lib/db'
import {getSession} from'../../../lib/auth'

async function auth(){const s=await getSession();if(!s)return{error:NextResponse.json({error:'No autorizado'},{status:401})};return{session:s}}
function data(b){return{expense_date:String(b.expense_date||'').slice(0,10),farm_id:Number(b.farm_id),category:String(b.category||'Otros').trim(),work_type:String(b.work_type||'Café').trim(),description:String(b.description||'').trim(),provider:String(b.provider||'').trim(),amount:Number(b.amount||0),payment_method:String(b.payment_method||'Efectivo').trim(),paid:b.paid!==false,notes:String(b.notes||'').trim()}}
function validate(x){if(!x.expense_date||!x.farm_id||!x.description)return'Fecha, finca y descripción son requeridos.';if(!(x.amount>0))return'El monto debe ser mayor que cero.';return''}
export async function GET(){const a=await auth();if(a.error)return a.error;const rows=await sql`SELECT e.*,f.name farm_name,u.full_name created_by_name FROM public.expenses e JOIN public.farms f ON f.id=e.farm_id LEFT JOIN public.users u ON u.id=e.created_by WHERE e.business_area='coffee' ORDER BY e.expense_date DESC,e.created_at DESC,e.id DESC`;return NextResponse.json({expenses:rows})}
export async function POST(req){const a=await auth();if(a.error)return a.error;if(a.session.role!=='admin')return NextResponse.json({error:'Solo administrador.'},{status:403});try{const x=data(await req.json()),er=validate(x);if(er)return NextResponse.json({error:er},{status:400});const r=await sql`INSERT INTO public.expenses(expense_date,farm_id,category,work_type,description,provider,amount,payment_method,paid,business_area,notes,created_by) VALUES(${x.expense_date},${x.farm_id},${x.category},${x.work_type},${x.description},${x.provider},${x.amount},${x.payment_method},${x.paid},'coffee',${x.notes||null},${a.session.id}) RETURNING id`;return NextResponse.json({ok:true,id:r[0]?.id})}catch(e){console.error(e);return NextResponse.json({error:'No se pudo registrar el gasto de café.'},{status:500})}}
