CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  full_name text NOT NULL DEFAULT '',
  role text NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin','viewer')),
  password_hash text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS farms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS workers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farm_id bigint NOT NULL REFERENCES farms(id),
  full_name text NOT NULL,
  identification text NOT NULL DEFAULT '',
  phone text NOT NULL DEFAULT '',
  hourly_rate numeric(12,2) NOT NULL DEFAULT 0 CHECK (hourly_rate >= 0),
  active boolean NOT NULL DEFAULT true,
  business_area text NOT NULL DEFAULT 'cafe' CHECK (business_area IN ('cafe','ganado','general')),
  created_by uuid NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS worker_weeks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id bigint NOT NULL REFERENCES workers(id) ON DELETE CASCADE,
  farm_id bigint NOT NULL REFERENCES farms(id),
  week_number smallint NOT NULL CHECK (week_number BETWEEN 1 AND 53),
  week_start date NOT NULL,
  week_end date NOT NULL,
  monday_hours numeric(5,2) NOT NULL DEFAULT 0 CHECK (monday_hours BETWEEN 0 AND 24),
  tuesday_hours numeric(5,2) NOT NULL DEFAULT 0 CHECK (tuesday_hours BETWEEN 0 AND 24),
  wednesday_hours numeric(5,2) NOT NULL DEFAULT 0 CHECK (wednesday_hours BETWEEN 0 AND 24),
  thursday_hours numeric(5,2) NOT NULL DEFAULT 0 CHECK (thursday_hours BETWEEN 0 AND 24),
  friday_hours numeric(5,2) NOT NULL DEFAULT 0 CHECK (friday_hours BETWEEN 0 AND 24),
  saturday_hours numeric(5,2) NOT NULL DEFAULT 0 CHECK (saturday_hours BETWEEN 0 AND 24),
  sunday_hours numeric(5,2) NOT NULL DEFAULT 0 CHECK (sunday_hours BETWEEN 0 AND 24),
  hourly_rate numeric(12,2) NOT NULL CHECK (hourly_rate >= 0),
  advances numeric(12,2) NOT NULL DEFAULT 0 CHECK (advances >= 0),
  deductions numeric(12,2) NOT NULL DEFAULT 0 CHECK (deductions >= 0),
  paid boolean NOT NULL DEFAULT false,
  payment_date date,
  notes text NOT NULL DEFAULT '',
  created_by uuid NOT NULL REFERENCES users(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(worker_id, week_start)
);

CREATE TABLE IF NOT EXISTS coffee_harvest (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  harvest_date date NOT NULL,
  week_number smallint NOT NULL CHECK (week_number BETWEEN 1 AND 53),
  farm_id bigint NOT NULL REFERENCES farms(id) ON DELETE RESTRICT,
  worker_id bigint NOT NULL REFERENCES workers(id) ON DELETE RESTRICT,
  quantity numeric(12,3) NOT NULL CHECK (quantity >= 0),
  unit text NOT NULL DEFAULT 'Cajuela',
  rate_per_unit numeric(12,2) NOT NULL CHECK (rate_per_unit >= 0),
  paid boolean NOT NULL DEFAULT false,
  notes text,
  created_by uuid NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS coffee_inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farm_id bigint REFERENCES farms(id),
  name text NOT NULL,
  category text NOT NULL,
  unit text NOT NULL,
  current_stock numeric(14,3) NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
  minimum_stock numeric(14,3) NOT NULL DEFAULT 0 CHECK (minimum_stock >= 0),
  lot_number text,
  expiration_date date,
  supplier text,
  active boolean NOT NULL DEFAULT true,
  notes text,
  created_by uuid NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS coffee_inventory_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_id bigint NOT NULL REFERENCES coffee_inventory(id),
  movement_date date NOT NULL DEFAULT CURRENT_DATE,
  movement_type text NOT NULL CHECK (movement_type IN ('entrada','salida','ajuste_positivo','ajuste_negativo')),
  quantity numeric(14,3) NOT NULL CHECK (quantity > 0),
  unit_cost numeric(14,2) CHECK (unit_cost IS NULL OR unit_cost >= 0),
  reference_type text,
  reference_id bigint,
  notes text,
  created_by uuid NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS farm_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_date date NOT NULL,
  farm_id bigint NOT NULL REFERENCES farms(id) ON DELETE RESTRICT,
  activity_type text NOT NULL CHECK (activity_type IN ('Fertilización','Abono')),
  method text NOT NULL CHECK (method IN ('Dron','Máquina estacionaria','Manual','Otro')),
  product text NOT NULL,
  dose numeric(14,3),
  dose_unit text,
  area numeric(14,3),
  area_unit text DEFAULT 'hectáreas',
  applied_by text,
  notes text,
  inventory_item_id bigint REFERENCES coffee_inventory(id),
  quantity_used numeric(14,3) CHECK (quantity_used IS NULL OR quantity_used > 0),
  created_by uuid NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cattle (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farm_id bigint NOT NULL REFERENCES farms(id),
  animal_identifier text NOT NULL,
  animal_name text,
  category text,
  breed text,
  sex text CHECK (sex IS NULL OR sex IN ('Macho','Hembra')),
  birth_date date,
  active boolean NOT NULL DEFAULT true,
  notes text,
  created_by uuid NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(farm_id, animal_identifier)
);

CREATE TABLE IF NOT EXISTS cattle_inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farm_id bigint REFERENCES farms(id),
  name text NOT NULL,
  category text NOT NULL,
  unit text NOT NULL,
  current_stock numeric(14,3) NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
  minimum_stock numeric(14,3) NOT NULL DEFAULT 0 CHECK (minimum_stock >= 0),
  lot_number text,
  expiration_date date,
  supplier text,
  active boolean NOT NULL DEFAULT true,
  notes text,
  created_by uuid NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cattle_inventory_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_id bigint NOT NULL REFERENCES cattle_inventory(id),
  movement_date date NOT NULL DEFAULT CURRENT_DATE,
  movement_type text NOT NULL CHECK (movement_type IN ('entrada','salida','ajuste_positivo','ajuste_negativo')),
  quantity numeric(14,3) NOT NULL CHECK (quantity > 0),
  unit_cost numeric(14,2) CHECK (unit_cost IS NULL OR unit_cost >= 0),
  reference_type text,
  reference_id bigint,
  notes text,
  created_by uuid NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cattle_treatments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_date date NOT NULL,
  farm_id bigint NOT NULL REFERENCES farms(id) ON DELETE RESTRICT,
  cattle_id bigint REFERENCES cattle(id),
  animal_identifier text NOT NULL,
  animal_name text,
  treatment_type text NOT NULL DEFAULT 'Inyección',
  product text NOT NULL,
  dose numeric(14,3),
  dose_unit text NOT NULL DEFAULT 'ml',
  route text,
  next_application_date date,
  applied_by text,
  notes text,
  inventory_item_id bigint REFERENCES cattle_inventory(id),
  created_by uuid NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS expenses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_date date NOT NULL,
  farm_id bigint NOT NULL REFERENCES farms(id),
  category text NOT NULL,
  work_type text NOT NULL,
  description text NOT NULL,
  provider text NOT NULL DEFAULT '',
  amount numeric(14,2) NOT NULL CHECK (amount > 0),
  payment_method text NOT NULL,
  paid boolean NOT NULL DEFAULT true,
  receipt_path text,
  receipt_name text,
  business_area text NOT NULL DEFAULT 'general' CHECK (business_area IN ('cafe','ganado','general')),
  created_by uuid NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS budgets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farm_id bigint NOT NULL REFERENCES farms(id),
  week_number smallint NOT NULL CHECK (week_number BETWEEN 1 AND 53),
  amount numeric(14,2) NOT NULL DEFAULT 0 CHECK (amount >= 0),
  updated_by uuid NOT NULL REFERENCES users(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(farm_id, week_number)
);

CREATE INDEX IF NOT EXISTS idx_workers_farm ON workers(farm_id);
CREATE INDEX IF NOT EXISTS idx_harvest_date_farm ON coffee_harvest(harvest_date, farm_id);
CREATE INDEX IF NOT EXISTS idx_applications_date_farm ON farm_applications(application_date, farm_id);
CREATE INDEX IF NOT EXISTS idx_cattle_farm ON cattle(farm_id);
CREATE INDEX IF NOT EXISTS idx_cattle_treatments_date ON cattle_treatments(application_date, farm_id);
CREATE INDEX IF NOT EXISTS idx_expenses_date_area ON expenses(expense_date, business_area, farm_id);
CREATE INDEX IF NOT EXISTS idx_coffee_inventory_active ON coffee_inventory(active, farm_id);
CREATE INDEX IF NOT EXISTS idx_cattle_inventory_active ON cattle_inventory(active, farm_id);

CREATE OR REPLACE FUNCTION apply_coffee_inventory_movement() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE delta numeric;
BEGIN
  delta := CASE WHEN NEW.movement_type IN ('entrada','ajuste_positivo') THEN NEW.quantity ELSE -NEW.quantity END;
  UPDATE coffee_inventory SET current_stock = current_stock + delta WHERE id = NEW.inventory_id AND current_stock + delta >= 0;
  IF NOT FOUND THEN RAISE EXCEPTION 'Inventario de café insuficiente o producto inexistente'; END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_coffee_inventory_movement ON coffee_inventory_movements;
CREATE TRIGGER trg_coffee_inventory_movement BEFORE INSERT ON coffee_inventory_movements FOR EACH ROW EXECUTE FUNCTION apply_coffee_inventory_movement();

CREATE OR REPLACE FUNCTION apply_cattle_inventory_movement() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE delta numeric;
BEGIN
  delta := CASE WHEN NEW.movement_type IN ('entrada','ajuste_positivo') THEN NEW.quantity ELSE -NEW.quantity END;
  UPDATE cattle_inventory SET current_stock = current_stock + delta WHERE id = NEW.inventory_id AND current_stock + delta >= 0;
  IF NOT FOUND THEN RAISE EXCEPTION 'Inventario de ganado insuficiente o producto inexistente'; END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_cattle_inventory_movement ON cattle_inventory_movements;
CREATE TRIGGER trg_cattle_inventory_movement BEFORE INSERT ON cattle_inventory_movements FOR EACH ROW EXECUTE FUNCTION apply_cattle_inventory_movement();

CREATE OR REPLACE FUNCTION deduct_coffee_application_inventory() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.inventory_item_id IS NOT NULL AND NEW.quantity_used IS NOT NULL THEN
    INSERT INTO coffee_inventory_movements(inventory_id,movement_date,movement_type,quantity,reference_type,reference_id,notes,created_by)
    VALUES(NEW.inventory_item_id,NEW.application_date,'salida',NEW.quantity_used,'farm_application',NEW.id,'Consumo automático por aplicación',NEW.created_by);
  END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_deduct_coffee_application ON farm_applications;
CREATE TRIGGER trg_deduct_coffee_application AFTER INSERT ON farm_applications FOR EACH ROW EXECUTE FUNCTION deduct_coffee_application_inventory();

CREATE OR REPLACE FUNCTION deduct_cattle_treatment_inventory() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.inventory_item_id IS NOT NULL AND NEW.dose IS NOT NULL THEN
    INSERT INTO cattle_inventory_movements(inventory_id,movement_date,movement_type,quantity,reference_type,reference_id,notes,created_by)
    VALUES(NEW.inventory_item_id,NEW.application_date,'salida',NEW.dose,'cattle_treatment',NEW.id,'Consumo automático por tratamiento',NEW.created_by);
  END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_deduct_cattle_treatment ON cattle_treatments;
CREATE TRIGGER trg_deduct_cattle_treatment AFTER INSERT ON cattle_treatments FOR EACH ROW EXECUTE FUNCTION deduct_cattle_treatment_inventory();
